'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import './admin.css';

const LABEL={reports:'Denuncias',routes:'Rutas propuestas',warnings:'Avisos de chat',errors:'Errores y alertas'};
export default function AdminConsole(){
 const[section,setSection]=useState('reports'),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{load()},[section]);
 const endpoint=section==='errors'?'/api/admin/monitoring':'/api/admin/moderation';
 async function request(options={}){const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Inicia sesión con la cuenta administradora.');const response=await fetch(endpoint,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error||'Error administrativo.');return body}
 async function load(){setLoading(true);setError('');try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Inicia sesión antes de abrir la consola.');const url=section==='errors'?endpoint:`${endpoint}?section=${section}`,response=await fetch(url,{headers:{Authorization:`Bearer ${token}`}}),body=await response.json();if(!response.ok)throw new Error(body.error);setItems(body.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function act(item,status){const notes=section==='errors'?'':window.prompt('Notas internas de revisión (opcional):','')||'';try{await request({method:'POST',body:JSON.stringify({section,id:item.id,status,notes})});await load()}catch(e){setError(e.message)}}
 return <main className="adminConsole"><header><div><small>ACCESO RESTRINGIDO</small><h1>Consola Encúmbrate</h1></div><a href="/">Volver</a></header><nav>{Object.keys(LABEL).map(key=><button key={key} className={section===key?'active':''} onClick={()=>setSection(key)}>{LABEL[key]}</button>)}</nav>{error&&<p className="adminError">{error}</p>}<section>{loading?<p>Actualizando cola…</p>:items.length?items.map(item=><article key={item.id||item.fingerprint} className={item.severity==='critical'?'criticalIncident':''}><small>{new Date(item.last_seen_at||item.created_at).toLocaleString('es-ES')}</small><h2>{item.name||item.reported_alias||item.reason||item.message||'Elemento pendiente'}</h2><p>{item.description||item.message_excerpt||item.risks||(item.route?`${item.source} · ${item.route}`:'Sin descripción.')}</p>{item.occurrences&&<b>{item.occurrences} apariciones</b>}{item.severity&&<b>{item.severity}</b>}{item.status&&<span>{item.status}</span>}<div>{section==='reports'&&<><button onClick={()=>act(item,'reviewing')}>En revisión</button><button onClick={()=>act(item,'resolved')}>Resolver</button><button onClick={()=>act(item,'dismissed')}>Descartar</button></>}{section==='routes'&&<><button onClick={()=>act(item,'approved')}>Aprobar</button><button onClick={()=>act(item,'needs_changes')}>Pedir cambios</button><button onClick={()=>act(item,'rejected')}>Rechazar</button><button onClick={()=>act(item,'duplicate')}>Duplicada</button></>}{section==='warnings'&&<><button onClick={()=>act(item,'reviewed')}>Revisado</button><button onClick={()=>act(item,'dismissed')}>Falso positivo</button><button onClick={()=>act(item,'sanctioned')}>Sancionar</button></>}{section==='errors'&&<><button onClick={()=>act({...item,id:item.fingerprint},'acknowledged')}>Reconocer</button><button onClick={()=>act({...item,id:item.fingerprint},'resolved')}>Resolver</button></>}</div></article>):<p>No hay elementos pendientes.</p>}</section></main>
}
