'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import './admin.css';

const LABEL={reports:'Denuncias',routes:'Rutas propuestas',warnings:'Avisos de chat'};
export default function AdminConsole(){
 const[section,setSection]=useState('reports'),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{load()},[section]);
 async function request(options={}){const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Inicia sesión con la cuenta administradora.');const response=await fetch('/api/admin/moderation',{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error||'Error administrativo.');return body}
 async function load(){setLoading(true);setError('');try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Inicia sesión antes de abrir la consola.');const response=await fetch(`/api/admin/moderation?section=${section}`,{headers:{Authorization:`Bearer ${token}`}}),body=await response.json();if(!response.ok)throw new Error(body.error);setItems(body.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function act(item,status){const notes=window.prompt('Notas internas de revisión (opcional):','')||'';try{await request({method:'POST',body:JSON.stringify({section,id:item.id,status,notes})});await load()}catch(e){setError(e.message)}}
 return <main className="adminConsole"><header><div><small>ACCESO RESTRINGIDO</small><h1>Consola Encúmbrate</h1></div><a href="/">Volver</a></header><nav>{Object.keys(LABEL).map(key=><button key={key} className={section===key?'active':''} onClick={()=>setSection(key)}>{LABEL[key]}</button>)}</nav>{error&&<p className="adminError">{error}</p>}<section>{loading?<p>Actualizando cola…</p>:items.length?items.map(item=><article key={item.id}><small>{new Date(item.created_at).toLocaleString('es-ES')}</small><h2>{item.name||item.reported_alias||item.reason||'Elemento pendiente'}</h2><p>{item.description||item.message_excerpt||item.risks||'Sin descripción.'}</p>{item.category&&<b>{item.category}</b>}{item.status&&<span>{item.status}</span>}<div>{section==='reports'&&<><button onClick={()=>act(item,'reviewing')}>En revisión</button><button onClick={()=>act(item,'resolved')}>Resolver</button><button onClick={()=>act(item,'dismissed')}>Descartar</button></>}{section==='routes'&&<><button onClick={()=>act(item,'approved')}>Aprobar</button><button onClick={()=>act(item,'needs_changes')}>Pedir cambios</button><button onClick={()=>act(item,'rejected')}>Rechazar</button><button onClick={()=>act(item,'duplicate')}>Duplicada</button></>}{section==='warnings'&&<><button onClick={()=>act(item,'reviewed')}>Revisado</button><button onClick={()=>act(item,'dismissed')}>Falso positivo</button><button onClick={()=>act(item,'sanctioned')}>Sancionar</button></>}</div></article>):<p>No hay elementos pendientes.</p>}</section></main>
}
