import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { getSupabaseAdmin } from '../../../../lib/supabase-admin';

export const dynamic='force-dynamic';
const ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
function haversine(a,b){const rad=value=>value*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function collectGeometry(element){const points=[];for(const member of element.members||[]){for(const point of member.geometry||[]){const next={lat:point.lat,lon:point.lon},previous=points.at(-1);if(!previous||previous.lat!==next.lat||previous.lon!==next.lon)points.push(next)}}return points}
function sample(points,max=240){if(points.length<=max)return points;const step=(points.length-1)/(max-1);return Array.from({length:max},(_,index)=>points[Math.round(index*step)])}
async function storedPoints(id){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;let route;if(url&&key){const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),{data,error}=await client.rpc('get_public_hiking_route_trace',{p_route_id:id});if(error)throw error;route=Array.isArray(data)?data[0]:data}else{const{data,error}=await getSupabaseAdmin().from('hiking_routes').select('raw_tags,source').eq('id',id).eq('published',true).maybeSingle();if(error)throw error;route=data?{trace_points:data.raw_tags?.trace_points,source:data.source}:null}const points=(route?.trace_points||[]).map(point=>({lat:Number(point?.[0]),lon:Number(point?.[1])})).filter(point=>Number.isFinite(point.lat)&&Number.isFinite(point.lon));return points.length>1?{points,source:route.source==='fedamon'?'FAM':'Catálogo oficial'}:null}
export async function GET(request){const raw=request.nextUrl.searchParams.get('id')||'',match=raw.match(/^osm-relation-(\d+)$/);if(!/^[a-z0-9-]+$/i.test(raw))return NextResponse.json({error:'Referencia de ruta no válida.'},{status:400});try{const stored=match?null:await storedPoints(raw);if(stored){let kilometres=0;for(let index=1;index<stored.points.length;index++)kilometres+=haversine(stored.points[index-1],stored.points[index]);return NextResponse.json({points:sample(stored.points),distanceKm:kilometres,source:stored.source,official:true},{headers:{'Cache-Control':'public, s-maxage=86400, stale-while-revalidate=604800'}})}}catch{}if(!match)return NextResponse.json({error:'El trazado navegable de esta ruta no está disponible ahora.'},{status:503});const query=`[out:json][timeout:20];relation(${match[1]});out geom;`;for(const endpoint of ENDPOINTS){try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({data:query}),signal:AbortSignal.timeout(18000),next:{revalidate:86400}});if(!response.ok)throw new Error();const data=await response.json(),points=collectGeometry(data.elements?.[0]||{});if(points.length<2)throw new Error();let kilometres=0;for(let index=1;index<points.length;index++)kilometres+=haversine(points[index-1],points[index]);return NextResponse.json({points:sample(points),distanceKm:kilometres,source:'OpenStreetMap',official:false},{headers:{'Cache-Control':'public, s-maxage=86400, stale-while-revalidate=604800'}})}catch{}}return NextResponse.json({error:'El trazado público de esta ruta no está disponible ahora.'},{status:503})}
