'use client';
import {useEffect,useState} from 'react';
import './compass-tools.css';
import './compass-course-entry.css';

const DIRECTIONS=['N','NE','E','SE','S','SO','O','NO'];
const COURSE=[
 {title:'Conoce las partes',icon:'⌖',text:'La flecha roja señala el norte. El número indica grados: norte 0°, este 90°, sur 180° y oeste 270°.',task:'Busca la N y recuerda que siempre representa el norte.'},
 {title:'Sujeta bien el móvil',icon:'▭',text:'Mantén el teléfono plano, alejado de llaves, hebillas, altavoces y objetos metálicos que alteran el sensor.',task:'Coloca el móvil horizontal a la altura de la cintura.'},
 {title:'Orienta un rumbo',icon:'↑',text:'Gira despacio hasta que el rumbo deseado quede arriba. Si buscas el este, detente aproximadamente en 90°.',task:'Practica encontrando primero el norte y después el este.'},
 {title:'Relaciona mapa y terreno',icon:'△',text:'Gira el mapa hasta que su norte coincida con el norte de la brújula. Identifica dos referencias visibles antes de avanzar.',task:'Busca una montaña, camino o edificio que también aparezca en el mapa.'},
 {title:'Úsala con seguridad',icon:'!',text:'Una brújula orienta, pero no confirma que el terreno sea transitable. No sigas un rumbo que cruce cortados, ríos, carreteras o fincas cerradas.',task:'Si estás perdido, detente y utiliza “Estoy perdido” o llama al 112.'}
];

export default function CompassTools(){
 const[open,setOpen]=useState(false),[course,setCourse]=useState(false),[courseStep,setCourseStep]=useState(0),[heading,setHeading]=useState(null),[error,setError]=useState('');
 useEffect(()=>{const show=()=>setOpen(true),learn=()=>{setCourseStep(0);setCourse(true)};window.addEventListener('encumbrate:open-compass',show);window.addEventListener('encumbrate:open-compass-course',learn);return()=>{window.removeEventListener('encumbrate:open-compass',show);window.removeEventListener('encumbrate:open-compass-course',learn)}},[]);
 useEffect(()=>{if(!open)return;let active=true;function orient(event){if(!active)return;const value=Number.isFinite(event.webkitCompassHeading)?event.webkitCompassHeading:Number.isFinite(event.alpha)?(360-event.alpha)%360:null;if(value!==null){setHeading(value);setError('')}}function attach(){window.addEventListener('deviceorientationabsolute',orient,true);window.addEventListener('deviceorientation',orient,true);setTimeout(()=>{if(active&&heading===null)setError('Mueve el móvil dibujando un 8 para calibrarlo. Si no cambia, este dispositivo no ofrece sensor de orientación.')},3500)}async function start(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted')return setError('Permiso de orientación no concedido. Actívalo en los ajustes del navegador.')}attach()}catch{setError('No hemos podido activar el sensor de orientación.')}}start();return()=>{active=false;window.removeEventListener('deviceorientationabsolute',orient,true);window.removeEventListener('deviceorientation',orient,true)}},[open]);
 const degrees=heading===null?0:Math.round(heading),direction=DIRECTIONS[Math.round(degrees/45)%8];
 return <>{open&&<aside className="compassWidget" aria-label="Brújula"><header><div><small>ORIENTACIÓN</small><strong>Brújula</strong></div><button onClick={()=>setOpen(false)} aria-label="Cerrar brújula">×</button></header><div className="compassDial"><div className="compassRose" style={{transform:`rotate(${-degrees}deg)`}}><b className="north">N</b><b className="east">E</b><b className="south">S</b><b className="west">O</b><i/></div><span className="compassIndex">▼</span></div><div className="compassReading"><strong>{heading===null?'—':`${degrees}° ${direction}`}</strong><small>{heading===null?'Esperando al sensor…':'Rumbo actual'}</small></div>{error&&<p>{error}</p>}<button className="compassLearn" onClick={()=>{setCourseStep(0);setCourse(true)}}>¿Cómo se utiliza?</button></aside>}{course&&<CompassCourse step={courseStep} setStep={setCourseStep} close={()=>setCourse(false)}/>}</>
}

function CompassCourse({step,setStep,close}){const item=COURSE[step],last=step===COURSE.length-1;return <section className="compassCourse" role="dialog" aria-modal="true"><header><button onClick={close}>×</button><small>CURSO DE SEGURIDAD</small><h1>Aprende a usar la brújula</h1><div>{COURSE.map((_,index)=><i key={index} className={index<=step?'active':''}/>)}</div></header><main><span className="courseCompassIcon">{item.icon}</span><small>PASO {step+1} DE {COURSE.length}</small><h2>{item.title}</h2><p>{item.text}</p><div className="courseTask"><b>Practica ahora</b><span>{item.task}</span></div><div className="courseButtons">{step>0&&<button onClick={()=>setStep(step-1)}>Atrás</button>}<button className="courseNext" onClick={()=>last?close():setStep(step+1)}>{last?'Terminar curso':'Lo entiendo · Siguiente'}</button></div></main></section>}
