'use client';

import { useEffect, useRef, useState } from 'react';
import {gpsFixUsable,navigationHeading,nearestPolylinePoint,plausibleGpsTransition,routeProximity} from '../lib/navigation-geometry';

export default function LiveRouteGuide({route,track,onBack,onLost,onFinish}){
  const nodeRef=useRef(null),mapRef=useRef(null),userRef=useRef(null),followingRef=useRef(true),previousFixRef=useRef(null),lastGoodAtRef=useRef(null),[position,setPosition]=useState(null),[offRoute,setOffRoute]=useState(null),[gpsState,setGpsState]=useState('searching'),[tileError,setTileError]=useState(false),[following,setFollowing]=useState(true);
  useEffect(()=>{followingRef.current=following},[following]);
  useEffect(()=>{let active=true;async function mount(){const L=(await import('leaflet')).default;if(!active||!nodeRef.current)return;const points=track.points.map(p=>[p.lat,p.lon]),map=L.map(nodeRef.current,{zoomControl:false,attributionControl:true});mapRef.current=map;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).on('tileerror',()=>setTileError(true)).addTo(map);L.polyline(points,{color:'#063d2c',weight:10,opacity:.72}).addTo(map);L.polyline(points,{color:'#78d443',weight:6,opacity:1}).addTo(map);map.fitBounds(L.latLngBounds(points),{padding:[30,30]});L.control.zoom({position:'bottomright'}).addTo(map);map.on('dragstart',()=>setFollowing(false))}mount();return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[track.id]);
  useEffect(()=>{if(!navigator.geolocation){setGpsState('unsupported');return}previousFixRef.current=null;lastGoodAtRef.current=null;const watchdog=setInterval(()=>{const last=lastGoodAtRef.current;if(last&&Date.now()-last>12000)setGpsState('paused')},2000),watch=navigator.geolocation.watchPosition(({coords,timestamp})=>{const candidate={lat:coords.latitude,lon:coords.longitude,accuracy:Number(coords.accuracy),heading:coords.heading,speed:coords.speed,at:Number(timestamp)||Date.now()};if(!gpsFixUsable(candidate)){setGpsState('weak');return}const previous=previousFixRef.current;if(!plausibleGpsTransition(previous,candidate)){setGpsState('weak');return}const current={...candidate,heading:navigationHeading(previous,candidate)};previousFixRef.current=current;lastGoodAtRef.current=Date.now();setPosition(current);const near=nearestPolylinePoint(current,track.points),proximity=routeProximity(near?.distance??Infinity,current.accuracy);setOffRoute(near?.distance??null);setGpsState(proximity.status);const map=mapRef.current;if(!map)return;import('leaflet').then(module=>{const L=module.default,icon=L.divIcon({className:'hikerArrowIcon',html:`<span style="transform:rotate(${current.heading}deg)">▲</span>`,iconSize:[44,44],iconAnchor:[22,22]});if(!userRef.current)userRef.current=L.marker([current.lat,current.lon],{icon,zIndexOffset:1000}).addTo(map);else userRef.current.setLatLng([current.lat,current.lon]).setIcon(icon);if(followingRef.current)map.setView([current.lat,current.lon],Math.max(map.getZoom(),16),{animate:true})})},(error)=>{setGpsState(error?.code===1?'denied':'paused')},{enableHighAccuracy:true,maximumAge:1000,timeout:12000});return()=>{clearInterval(watchdog);navigator.geolocation.clearWatch(watch)}},[track.id]);
  const statusTitle=gpsState==='searching'?'Buscando GPS…':gpsState==='unsupported'?'GPS no disponible':gpsState==='denied'?'Permiso de ubicación bloqueado':gpsState==='paused'?'Señal GPS interrumpida':gpsState==='weak'?'Precisión GPS insuficiente':gpsState==='on-track'?'Vas por el sendero':gpsState==='near'?'Cerca del trazado':gpsState==='uncertain'?'Posición aproximada':offRoute!==null?`A ${Math.round(offRoute)} m del sendero`:'Buscando GPS…';
  return <div className="liveGuide" role="dialog" aria-modal="true" aria-label={`Guía de ${route.name}`}><div ref={nodeRef} className="liveGuideMap"/><header><button onClick={onBack} aria-label="Volver">‹</button><div><small>NAVEGACIÓN ACTIVA</small><strong>{route.name}</strong></div></header><div className="liveGuideStatus"><span className={gpsState==='off-route'?'warning':'ok'}/><div><strong>{statusTitle}</strong><small>{position?`Precisión GPS ±${Math.round(position.accuracy)} m`:'Mantén la ubicación activada'}</small></div></div>{tileError&&<div className="liveGuideOffline">Sin cobertura cartográfica · el trazado verde y el GPS siguen activos</div>}<button className="recenterGuide" onClick={()=>{setFollowing(true);if(position)mapRef.current?.setView([position.lat,position.lon],16)}}>⌖ Centrarme</button><div className="liveGuideActions"><button onClick={onLost}>⚠ Estoy perdido</button><button onClick={onFinish}>Finalizar ruta</button></div></div>
}
