'use client';

import { useEffect, useRef, useState } from 'react';

function distance(a,b){const rad=v=>v*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function nearest(position,points){let point=points[0],km=Infinity;for(const candidate of points){const next=distance(position,candidate);if(next<km){km=next;point=candidate}}return{point,km}}

export default function LiveRouteGuide({route,track,onBack,onLost,onFinish}){
  const nodeRef=useRef(null),mapRef=useRef(null),userRef=useRef(null),[position,setPosition]=useState(null),[offRoute,setOffRoute]=useState(null),[tileError,setTileError]=useState(false),[following,setFollowing]=useState(true);
  useEffect(()=>{let active=true;async function mount(){const L=(await import('leaflet')).default;if(!active||!nodeRef.current)return;const points=track.points.map(p=>[p.lat,p.lon]),map=L.map(nodeRef.current,{zoomControl:false,attributionControl:true});mapRef.current=map;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).on('tileerror',()=>setTileError(true)).addTo(map);L.polyline(points,{color:'#063d2c',weight:10,opacity:.72}).addTo(map);L.polyline(points,{color:'#78d443',weight:6,opacity:1}).addTo(map);map.fitBounds(L.latLngBounds(points),{padding:[30,30]});L.control.zoom({position:'bottomright'}).addTo(map);map.on('dragstart',()=>setFollowing(false))}mount();return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[track.id]);
  useEffect(()=>{if(!navigator.geolocation)return;const watch=navigator.geolocation.watchPosition(({coords})=>{const current={lat:coords.latitude,lon:coords.longitude,accuracy:coords.accuracy,heading:Number.isFinite(coords.heading)?coords.heading:0};setPosition(current);const near=nearest(current,track.points);setOffRoute(near.km*1000);const map=mapRef.current;if(!map)return;import('leaflet').then(module=>{const L=module.default,icon=L.divIcon({className:'hikerArrowIcon',html:`<span style="transform:rotate(${current.heading}deg)">▲</span>`,iconSize:[44,44],iconAnchor:[22,22]});if(!userRef.current)userRef.current=L.marker([current.lat,current.lon],{icon,zIndexOffset:1000}).addTo(map);else userRef.current.setLatLng([current.lat,current.lon]).setIcon(icon);if(following)map.setView([current.lat,current.lon],Math.max(map.getZoom(),16),{animate:true})})},()=>{}, {enableHighAccuracy:true,maximumAge:2000,timeout:15000});return()=>navigator.geolocation.clearWatch(watch)},[track.id,following]);
  return <div className="liveGuide" role="dialog" aria-modal="true" aria-label={`Guía de ${route.name}`}><div ref={nodeRef} className="liveGuideMap"/><header><button onClick={onBack} aria-label="Volver">‹</button><div><small>NAVEGACIÓN ACTIVA</small><strong>{route.name}</strong></div></header><div className="liveGuideStatus"><span className={offRoute!==null&&offRoute>50?'warning':'ok'}/><div><strong>{offRoute===null?'Buscando GPS…':offRoute<=25?'Vas por el sendero':offRoute<=50?'Cerca del trazado':`A ${Math.round(offRoute)} m del sendero`}</strong><small>{position?`Precisión GPS ±${Math.round(position.accuracy)} m`:'Mantén la ubicación activada'}</small></div></div>{tileError&&<div className="liveGuideOffline">Sin cobertura cartográfica · el trazado verde y el GPS siguen activos</div>}<button className="recenterGuide" onClick={()=>{setFollowing(true);if(position)mapRef.current?.setView([position.lat,position.lon],16)}}>⌖ Centrarme</button><div className="liveGuideActions"><button onClick={onLost}>⚠ Estoy perdido</button><button onClick={onFinish}>Finalizar ruta</button></div></div>
}
