'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import './meetups.css';
import './meetups-fab.css';
import SocialChat from './SocialChat';

const LEVEL={principiante:'Principiante',intermedio:'Intermedio',experto:'Experto'};
const PACE={tranquilo:'Tranquilo',normal:'Normal',rapido:'Rápido'};
const publicName=user=>(user?.user_metadata?.name||user?.user_metadata?.full_name||'Senderista').trim().slice(0,60);
const dateText=value=>new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));

export default function Meetups(){
 const[open,setOpen]=useState(false),[user,setUser]=useState(null),[route,setRoute]=useState(null),[tab,setTab]=useState('upcoming'),[meetups,setMeetups]=useState([]),[members,setMembers]=useState([]),[loading,setLoading]=useState(false),[formOpen,setFormOpen]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data?.user||null))},[]);
 useEffect(()=>{const show=event=>{setRoute(event.detail||null);setFormOpen(Boolean(event.detail));setOpen(true);setMessage('')};window.addEventListener('encumbrate:open-meetups',show);window.addEventListener('encumbrate:create-meetup',show);return()=>{window.removeEventListener('encumbrate:open-meetups',show);window.removeEventListener('encumbrate:create-meetup',show)}},[]);
 useEffect(()=>{if(open&&user)load()},[open,user]);
 async function load(){setLoading(true);const now=new Date().toISOString();const[{data:list,error},{data:mine}]=await Promise.all([supabase.from('route_meetups').select('*').gte('starts_at',now).order('starts_at'),supabase.from('route_meetup_members').select('*').eq('user_id',user.id)]);setMeetups(list||[]);setMembers(mine||[]);setMessage(error?'No hemos podido cargar las quedadas.':'');setLoading(false)}
 const membership=useMemo(()=>Object.fromEntries(members.map(item=>[item.meetup_id,item])),[members]);
 const visible=tab==='mine'?meetups.filter(item=>item.organizer_id===user?.id||membership[item.id]):meetups.filter(item=>item.status==='scheduled');
 async function join(item){setMessage('Solicitando plaza…');const{error}=await supabase.rpc('request_meetup_place',{p_meetup_id:item.id,p_member_name:publicName(user)});setMessage(error?'No se ha podido solicitar la plaza.':'Solicitud enviada al organizador.');await load()}
 async function create(event){event.preventDefault();const data=new FormData(event.currentTarget),startsAt=new Date(data.get('starts_at')).toISOString();setMessage('Creando quedada…');const payload={organizer_id:user.id,organizer_name:publicName(user),external_route_key:route.id,route_name:route.name,province:route.province||null,municipality:route.municipality||null,starts_at:startsAt,meeting_point_name:String(data.get('meeting_point')).trim(),capacity:Number(data.get('capacity')),pace:data.get('pace'),required_level:data.get('level'),description:String(data.get('description')).trim()||null,adults_only:true,safety_acknowledged:data.get('safety')==='on'};const{error}=await supabase.from('route_meetups').insert(payload);if(error){setMessage(error.message?.includes('check')?'Revisa la fecha y los datos de la quedada.':'No hemos podido crear la quedada.');return}setFormOpen(false);setTab('mine');setMessage('¡Quedada creada! Ya pueden solicitar plaza.');await load()}
 if(!open||!user)return null;
 return <div className="meetupsScreen" role="dialog" aria-modal="true"><header><button onClick={()=>setOpen(false)} aria-label="Volver">‹</button><div><small>COMUNIDAD</small><h1>Quedadas Encúmbrate</h1></div><span>♧</span></header><div className="meetupsHero"><strong>La montaña se disfruta en compañía</strong><p>Encuentra senderistas de toda España y organiza una salida segura.</p></div><nav><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Próximas</button><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>Mis quedadas</button></nav><SocialChat user={user}/>{message&&<p className="meetupMessage">{message}</p>}{formOpen&&route?<MeetupForm route={route} close={()=>setFormOpen(false)} submit={create}/>:<main>{loading?<div className="meetupEmpty">Buscando próximas aventuras…</div>:visible.length?visible.map(item=><MeetupCard key={item.id} item={item} own={item.organizer_id===user.id} membership={membership[item.id]} join={join}/>):<div className="meetupEmpty"><span>△</span><strong>Aún no hay quedadas aquí</strong><p>Abre cualquier ruta y pulsa “Crear quedada” para ser la primera persona en organizarla.</p></div>}</main>}<footer><p>Solo para mayores de 18 años. Las quedadas son encuentros informales entre particulares y no sustituyen a un guía profesional.</p></footer></div>
}

function MeetupCard({item,own,membership,join}){const full=item.participant_count>=item.capacity;return <article className="meetupCard"><div className="meetupDate"><b>{new Date(item.starts_at).getDate()}</b><small>{new Intl.DateTimeFormat('es-ES',{month:'short'}).format(new Date(item.starts_at))}</small></div><div className="meetupInfo"><small>{item.municipality||item.province||'España'} · {dateText(item.starts_at)}</small><h2>{item.route_name}</h2><p>⌖ {item.meeting_point_name}</p><div><span>{LEVEL[item.required_level]}</span><span>Ritmo {PACE[item.pace]}</span><span>{item.participant_count}/{item.capacity} plazas</span></div><p className="meetupOrganizer">Organiza <b>{item.organizer_name}</b></p>{own?<b className="meetupStatus own">Eres quien organiza</b>:membership?<b className={`meetupStatus ${membership.status}`}>{membership.status==='pending'?'Solicitud pendiente':membership.status==='approved'?'Plaza confirmada':membership.status==='rejected'?'Solicitud no aceptada':'Solicitud cancelada'}</b>:<button disabled={full} onClick={()=>join(item)}>{full?'Completa':'Solicitar plaza'}</button>}</div></article>}

function MeetupForm({route,close,submit}){const tomorrow=new Date(Date.now()+86400000);tomorrow.setMinutes(tomorrow.getMinutes()-tomorrow.getTimezoneOffset());return <form className="meetupForm" onSubmit={submit}><button type="button" className="formClose" onClick={close}>×</button><small>NUEVA QUEDADA</small><h2>{route.name}</h2><label>Fecha y hora<input required name="starts_at" type="datetime-local" min={tomorrow.toISOString().slice(0,16)}/></label><label>Punto de encuentro público<input required minLength="3" maxLength="160" name="meeting_point" placeholder="Ej. aparcamiento del centro de visitantes"/></label><div className="meetupFormRow"><label>Plazas<select name="capacity" defaultValue="8">{[4,6,8,10,12,15,20,25,30].map(n=><option key={n}>{n}</option>)}</select></label><label>Ritmo<select name="pace" defaultValue="normal"><option value="tranquilo">Tranquilo</option><option value="normal">Normal</option><option value="rapido">Rápido</option></select></label></div><label>Nivel recomendado<select name="level" defaultValue={route.level||'principiante'}><option value="principiante">Principiante</option><option value="intermedio">Intermedio</option><option value="experto">Experto</option></select></label><label>Información para el grupo<textarea name="description" maxLength="1000" placeholder="Material, experiencia o indicaciones útiles…"/></label><label className="meetupCheck"><input required name="safety" type="checkbox"/><span>Confirmo que soy mayor de 18 años, que el lugar es público y que esta es una quedada informal, no un servicio profesional de guía.</span></label><button className="createMeetup">Publicar quedada</button></form>}
