'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {SPAIN_TERRITORIES,offlineRegionId} from '../lib/offline-regions';
import {countryOfflinePackSpec,downloadOfflinePack,estimateOfflinePackBytes,listOfflinePacks,offlineMosaicStats,removeOfflinePack} from '../lib/offline-mosaic';

function formatBytes(value){const b=Number(value||0);if(!Number.isFinite(b)||b<=0)return'0 MB';if(b<1048576)return`${Math.max(1,Math.round(b/1024))} KB`;if(b<1073741824)return`${(b/1048576).toLocaleString('es-ES',{maximumFractionDigits:1})} MB`;return`${(b/1073741824).toLocaleString('es-ES',{maximumFractionDigits:2})} GB`}
const KIND={country:'España completa',community:'Comunidad autónoma',province:'Provincia',route:'Ruta'};
export default function OfflineMapManager(){
 const communities=Object.keys(SPAIN_TERRITORIES),[community,setCommunity]=useState(communities[0]),[province,setProvince]=useState(SPAIN_TERRITORIES[communities[0]][0]),[packs,setPacks]=useState([]),[stats,setStats]=useState({bytes:0,tileCount:0}),[quota,setQuota]=useState(null),[working,setWorking]=useState(''),[progress,setProgress]=useState(null),[message,setMessage]=useState('');
 const refresh=useCallback(async()=>{try{const[s,m,q]=await Promise.all([listOfflinePacks(),offlineMosaicStats(),navigator.storage?.estimate?.().catch(()=>null)]);setPacks(s);setStats(m);setQuota(q||null)}catch{setMessage('No se ha podido consultar el almacén de mapas offline.')}},[]);
 useEffect(()=>{refresh();const sync=()=>refresh();window.addEventListener('encumbrate:offline-mosaic',sync);return()=>window.removeEventListener('encumbrate:offline-mosaic',sync)},[refresh]);
 useEffect(()=>setProvince(SPAIN_TERRITORIES[community]?.[0]||''),[community]);
 const used=useMemo(()=>quota?.quota?Math.min(100,Math.round(Number(quota.usage||0)/Number(quota.quota)*100)):null,[quota]);
 async function spec(kind,name){if(kind==='country')return countryOfflinePackSpec();const r=await fetch(`/api/maps/offline/regions?kind=${encodeURIComponent(kind)}&name=${encodeURIComponent(name)}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'No se ha podido preparar esta zona.');return b}
 async function download(kind,name){if(!navigator.onLine)return setMessage('Necesitas conexión para descargar una zona nueva. Los mapas ya guardados siguen funcionando offline.');setWorking(`${kind}:${name}`);setProgress({percentage:0,completed:0,total:0,bytes:0});setMessage('Preparando zona y comprobando espacio…');try{const s=await spec(kind,name),est=estimateOfflinePackBytes(s.bounds,s.minZoom,s.maxZoom);setMessage(`${s.name}: tamaño estimado ${formatBytes(est)}. Iniciando descarga…`);const p=await downloadOfflinePack(s,{onProgress:setProgress});setMessage(`${p.name} descargado y disponible sin conexión.`);await refresh()}catch(e){setMessage(e?.message||'No se ha podido completar la descarga.')}finally{setWorking('');setProgress(null)}}
 async function remove(pack){if(!window.confirm(`¿Eliminar «${pack.name}» del mapa offline de este dispositivo?`))return;setWorking(pack.id);try{await removeOfflinePack(pack.id);setMessage(`${pack.name} eliminado.`);await refresh()}catch(e){setMessage(e?.message||'No se ha podido eliminar el mapa.')}finally{setWorking('')}}
 const country=countryOfflinePackSpec(),countryPack=packs.find(p=>p.id===country.id&&p.status==='ready');
 return <section className="offlineMapManager" aria-label="Gestor de mapas offline">
  <div className="offlineManagerIntro"><div><small>MAPAS OFFLINE</small><h3>Gestor de mapas</h3><p>España se guarda en zoom bajo/medio. Añade detalle alto solo en comunidades, provincias o rutas concretas.</p></div><div className="offlineStorage"><strong>{formatBytes(stats.bytes)}</strong><span>{stats.tileCount.toLocaleString('es-ES')} teselas guardadas</span>{used!==null&&<small>{used}% del almacenamiento del navegador en uso</small>}</div></div>
  <div className="offlineZoneGrid">
   <article className="offlineZoneCard featured"><div><small>BASE NACIONAL · ZOOM 5–9</small><strong>🇪🇸 España completa</strong><span>{countryPack?'Descargado y disponible sin conexión':'Cobertura base nacional optimizada.'}</span></div><button type="button" disabled={Boolean(working)||Boolean(countryPack)} onClick={()=>download('country','España')}>{countryPack?'✓ Descargado':working==='country:España'?'Descargando…':'Descargar España'}</button></article>
   <article className="offlineZoneCard"><div><small>DETALLE · ZOOM 7–12</small><strong>Comunidad autónoma</strong><label>Elegir comunidad<select value={community} onChange={e=>setCommunity(e.target.value)}>{communities.map(n=><option key={n}>{n}</option>)}</select></label></div><button type="button" disabled={Boolean(working)} onClick={()=>download('community',community)}>{packs.some(p=>p.id===offlineRegionId('community',community)&&p.status==='ready')?'Actualizar comunidad':working===`community:${community}`?'Descargando…':'Descargar comunidad'}</button></article>
   <article className="offlineZoneCard"><div><small>DETALLE · ZOOM 8–13</small><strong>Provincia</strong><label>Comunidad<select value={community} onChange={e=>setCommunity(e.target.value)}>{communities.map(n=><option key={n}>{n}</option>)}</select></label><label>Provincia<select value={province} onChange={e=>setProvince(e.target.value)}>{(SPAIN_TERRITORIES[community]||[]).map(n=><option key={n}>{n}</option>)}</select></label></div><button type="button" disabled={Boolean(working)||!province} onClick={()=>download('province',province)}>{packs.some(p=>p.id===offlineRegionId('province',province)&&p.status==='ready')?'Actualizar provincia':working===`province:${province}`?'Descargando…':'Descargar provincia'}</button></article>
  </div>
  {progress&&<div className="offlineDownloadProgress" role="status"><div><i style={{width:`${Math.max(2,progress.percentage||0)}%`}}/></div><strong>{progress.percentage||0}%</strong><span>{progress.total?`${progress.completed.toLocaleString('es-ES')} / ${progress.total.toLocaleString('es-ES')} teselas · `:''}{formatBytes(progress.bytes)}</span></div>}
  {message&&<p className="offlineManagerMessage" role="status">{message}</p>}
  <div className="offlineInstalled"><div className="offlineInstalledTitle"><h4>Descargas de este dispositivo</h4><span>{packs.length} zonas · {formatBytes(stats.bytes)}</span></div>{packs.length?packs.map(p=><div className="offlinePack" key={p.id}><div><strong>{p.name}</strong><span>{KIND[p.kind]||'Zona'} · zoom {p.minZoom}–{p.maxZoom}</span><small>{p.status==='ready'?'✓ Descargado':`Descarga parcial · ${p.completedTiles||0}/${p.totalTiles||0}`} · {formatBytes(p.totalBytes)}</small></div><button type="button" disabled={Boolean(working)} onClick={()=>remove(p)}>Eliminar</button></div>):<p>No hay mosaicos descargados todavía.</p>}</div>
  <p className="offlineManagerNote">Las zonas comparten teselas: si una provincia coincide con España o una comunidad, la misma imagen no se duplica. El raster antiguo de ruta se mantiene como respaldo.</p>
 </section>
}
