'use client';
import {useMemo,useState} from 'react';
const routes=[
{id:1,name:'Ruta del Cares',place:'Picos de Europa · Asturias/León',level:2,km:24,up:650,hours:'6–7 h',score:4.9,tags:['Desfiladero','Vistas'],fit:68,desc:'Travesía espectacular entre paredes calizas.',risk:'Sendero expuesto en algunos puntos.',offline:true},
{id:2,name:'Bosque de Muniellos',place:'Asturias',level:1,km:8.4,up:260,hours:'3 h',score:4.8,tags:['Bosque','Fauna'],fit:96,desc:'Bosque atlántico para aprender a caminar con calma.',risk:'Reserva y normativa pueden aplicar.',offline:true},
{id:3,name:'Peñalara',place:'Sierra de Guadarrama · Madrid',level:2,km:11,up:620,hours:'4–5 h',score:4.8,tags:['Cumbre','Lagunas'],fit:74,desc:'Ascensión clásica con ambiente de montaña.',risk:'Meteorología cambiante en altura.',offline:true},
{id:4,name:'Mulhacén desde Capileira',place:'Sierra Nevada · Granada',level:3,km:23,up:1450,hours:'8–10 h',score:4.9,tags:['Alta montaña','Cumbre'],fit:31,desc:'Gran jornada de alta montaña.',risk:'No recomendada sin experiencia contrastada.',offline:true},
{id:5,name:'Faro del Caballo',place:'Santoña · Cantabria',level:2,km:10,up:520,hours:'3–4 h',score:4.7,tags:['Costa','Bosque'],fit:70,desc:'Bosque, acantilados y escaleras frente al Cantábrico.',risk:'Escaleras exigentes y terreno húmedo.',offline:true},
{id:6,name:'Barranco del Infierno',place:'Vall de Laguar · Alicante',level:2,km:14.5,up:820,hours:'5–6 h',score:4.8,tags:['Barranco','Escalones'],fit:57,desc:'Un clásico exigente de Alicante.',risk:'Desnivel y calor pueden elevar la exigencia.',offline:true}];
const names=['Principiante','Intermedio','Experto'];
export default function Home(){const[tab,setTab]=useState('inicio'),[profile,setProfile]=useState(null),[quiz,setQuiz]=useState(false),[answers,setAnswers]=useState({exp:0,dist:0,orient:0,aid:0,terrain:0}),[query,setQuery]=useState(''),[active,setActive]=useState(null),[done,setDone]=useState([]),[partial,setPartial]=useState({}),[sos,setSos]=useState(false),[loc,setLoc]=useState(null),[compass,setCompass]=useState(false),[music,setMusic]=useState(false);
const filtered=useMemo(()=>routes.filter(r=>(r.name+r.place+r.tags.join(' ')).toLowerCase().includes(query.toLowerCase())),[query]);
function finishQuiz(){let s=Object.values(answers).reduce((a,b)=>a+Number(b),0);let lvl=s>=12?3:s>=7?2:1;setProfile({level:lvl,score:s,orientation:Math.min(100,20+answers.orient*25),safety:Math.min(100,20+answers.aid*25),experience:Math.min(100,20+answers.exp*25)});setQuiz(false)}
function locate(){if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>setLoc({lat:p.coords.latitude,lon:p.coords.longitude,acc:Math.round(p.coords.accuracy)}),()=>{}, {enableHighAccuracy:true})}
const allowed=r=>profile&&r.level<=profile.level;
return <main><header><button className="brand" onClick={()=>setTab('inicio')}>▲ <b>Cumbre</b><span>Tu guía de montaña</span></button><button className="sosTop" onClick={()=>{setSos(true);locate()}}>SOS</button></header>
<section className="forestHero"><div className="heroShade"><p className="eyebrow">DESCUBRE · PREPARA · VIVE · PROTÉGETE</p><h1>Tu próxima aventura,<br/><i>a tu medida.</i></h1><p>Cumbre aprende de tu experiencia y te recomienda rutas que encajan contigo. Sin competir. Sin saltarte etapas.</p>{!profile?<button onClick={()=>setQuiz(true)}>Crear mi perfil senderista →</button>:<div className="profilePill"><b>{names[profile.level-1]}</b><span>Perfil calculado · no elegido manualmente</span></div>}</div></section>
<nav>{[['inicio','⌂','Inicio'],['explorar','⌕','Explorar'],['aventura','◉','Aventura'],['progreso','◎','Progreso'],['comunidad','♧','Experiencias']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}><b>{x[1]}</b>{x[2]}</button>)}</nav>
{tab==='inicio'&&<section className="content"><div className="welcome"><div><p className="eyebrow">¿QUÉ QUIERES HACER HOY?</p><h2>Nosotros buscamos la ruta.</h2></div><div className="quick"><button onClick={()=>setTab('explorar')}>✨ Sorpréndeme</button><button onClick={()=>setTab('explorar')}>📍 Cerca de mí</button><button onClick={()=>setTab('progreso')}>🏔 Quiero progresar</button></div></div>{profile?<><div className="cap"><h3>Tu capacidad senderista</h3><Meter n="Experiencia" v={profile.experience}/><Meter n="Orientación" v={profile.orientation}/><Meter n="Seguridad" v={profile.safety}/><small>El perfil evoluciona con cuestionario, rutas GPS verificadas y experiencia declarada.</small></div><h2>Perfectas para tu perfil</h2><div className="cards">{routes.filter(allowed).slice(0,3).map(r=><Card key={r.id} r={r} allowed profile={profile} open={()=>setActive(r)}/>)}</div></>:<div className="onboard"><b>Empieza con seguridad</b><p>No te pediremos que decidas si eres principiante o experto. Un breve cuestionario de experiencia, orientación y primeros auxilios crea tu punto de partida.</p><button onClick={()=>setQuiz(true)}>Evaluar mi experiencia</button></div>}<Safety onSOS={()=>{setSos(true);locate()}}/></section>}
{tab==='explorar'&&<section className="content"><p className="eyebrow">RUTAS DE ESPAÑA</p><h2>Explorar</h2><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Provincia, paisaje o ruta…"/></div><div className="cards">{filtered.map(r=><Card key={r.id} r={r} allowed={allowed(r)} profile={profile} open={()=>setActive(r)}/>)}</div></section>}
{tab==='aventura'&&<section className="content"><p className="eyebrow">MODO AVENTURA</p><h2>Todo lo importante, a una pulsación.</h2><div className="adventureGrid"><Tool icon="🗺" title="Mapa offline" text="Descarga track, mapa y puntos esenciales antes de salir."/><Tool icon="↩" title="Volver sobre mis pasos" text="Guarda tu rastro GPS para ayudarte a retroceder si te desorientas."/><Tool icon="🧭" title="Brújula" text="Rumbo, orientación y pequeño manual práctico." click={()=>setCompass(true)}/><Tool icon="⌚" title="Reloj" text="Preparado para integrar métricas de salud y actividad compatibles."/><Tool icon="🎵" title="Música" text="Abre tu plataforma favorita; el audio de seguridad tiene prioridad." click={()=>setMusic(true)}/><Tool icon="📸" title="Momentos" text="Hitos fotográficos inteligentes cuando estés en un lugar apropiado."/><Tool icon="⚠" title="Fuera de ruta" text="Detección de desviación y recuperación conservadora del track."/><Tool icon="🆘" title="SOS" text="GPS, coordenadas, compartir posición y llamada al 112." click={()=>{setSos(true);locate()}}/></div></section>}
{tab==='progreso'&&<section className="content"><p className="eyebrow">PASAPORTE DE MONTAÑA</p><h2>Tu historia no son solo kilómetros.</h2><div className="stats"><article><strong>{done.length}</strong><span>Completadas GPS</span></article><article><strong>{Object.keys(partial).length}</strong><span>Pendientes</span></article><article><strong>{done.reduce((a,id)=>a+(routes.find(r=>r.id===id)?.km||0),0).toFixed(1)}</strong><span>km verificados</span></article></div><div className="journal"><h3>Aventuras pendientes</h3>{Object.entries(partial).length?Object.entries(partial).map(([id,p])=>{let r=routes.find(x=>x.id==id);return <article key={id}><b>{r.name}</b><span>{p}% realizado · {(r.km*(1-p/100)).toFixed(1)} km aprox. pendientes</span><progress value={p} max="100"/></article>}):<p>Las rutas parciales permanecerán aquí hasta completarlas.</p>}<h3>Rutas completadas</h3>{done.length?done.map(id=><p key={id}>✓ {routes.find(r=>r.id===id).name} · track verificado</p>):<p>Aún no hay rutas verificadas.</p>}</div></section>}
{tab==='comunidad'&&<section className="content"><p className="eyebrow">EXPERIENCIAS VERIFICADAS</p><h2>Mira la ruta antes de vivirla.</h2><div className="photoStrip"><div>🌲<span>km 1,2 · bosque</span></div><div>🏔️<span>km 5,4 · mirador</span></div><div>🥾<span>km 8,1 · sendero</span></div></div><div className="community"><article><b>Laura · Ruta realizada ✓</b><p>Sendero limpio. Mucho viento arriba; el cortavientos me vino genial.</p><small>Estado · Equipamiento · Foto · Consejo</small></article><article><b>Miguel · Ruta realizada ✓</b><p>La fuente estaba seca. Recomiendo llevar el agua desde el inicio.</p><small>Información reciente de otros senderistas</small></article></div><p className="moderation">La comunidad prioriza consejos útiles. Insultos, amenazas, spam y contenido abusivo no se publican; una crítica negativa útil sí.</p></section>}
{active&&<div className="overlay"><section className="routeModal"><button className="close" onClick={()=>setActive(null)}>×</button><p className="eyebrow">{active.place}</p><h2>{active.name}</h2><div className="fit"><strong>{profile?active.fit:'—'}%</strong><span>compatibilidad orientativa con tu perfil</span></div><div className="metrics"><span>{active.km} km</span><span>↗ {active.up} m</span><span>{active.hours}</span></div><p>{active.desc}</p><div className="risk">⚠ {active.risk}</div>{!profile?<button onClick={()=>{setActive(null);setQuiz(true)}}>Crear perfil para saber si es adecuada</button>:allowed(active)?<><button onClick={()=>{setTab('aventura');setActive(null)}}>🥾 Preparar esta aventura</button><button className="secondary" onClick={()=>setPartial({...partial,[active.id]:42})}>Simular registro parcial 42%</button><button className="secondary" onClick={()=>{setDone([...new Set([...done,active.id])]);let n={...partial};delete n[active.id];setPartial(n)}}>Simular ruta GPS completada</button></>:<div className="locked"><b>🔒 Aún no recomendada para tu perfil</b><p>Podrás convertirla en objetivo, pero Cumbre no la propone como ruta realizable hasta que tu experiencia verificada sea adecuada.</p></div>}</section></div>}
{quiz&&<Quiz answers={answers} setAnswers={setAnswers} finish={finishQuiz} close={()=>setQuiz(false)}/>} {sos&&<SOS loc={loc} close={()=>setSos(false)}/>} {compass&&<Info title="🧭 Brújula y orientación" close={()=>setCompass(false)}><p><b>1.</b> Identifica norte, sur, este y oeste. <b>2.</b> Comprueba el rumbo antes de avanzar. <b>3.</b> Si pierdes el sendero, detente y revisa tu último punto conocido. <b>4.</b> No cruces terreno desconocido solo por seguir una flecha.</p><p>La brújula del móvil puede sufrir interferencias. En montaña avanzada lleva también mapa y medios de orientación adecuados.</p></Info>} {music&&<Info title="🎵 Música en ruta" close={()=>setMusic(false)}><p>Conecta auriculares o altavoz desde Bluetooth del teléfono y abre tu plataforma musical habitual. Cumbre no aloja música ni sustituye sus aplicaciones.</p><div className="musicBtns"><button>Spotify</button><button>Apple Music</button><button>YouTube Music</button></div><p>En el producto nativo, avisos de navegación y seguridad tendrán prioridad cuando la plataforma lo permita.</p></Info>}
<footer><b>▲ Cumbre</b><span>Senderismo inteligente · España</span><small>Las recomendaciones reducen incertidumbre, pero no garantizan seguridad. Condiciones, salud, GPS y meteorología pueden cambiar.</small></footer></main>}
function Card({r,allowed,profile,open}){return <article className={'route '+(!allowed?'blocked':'')}><div className="routeImg"><b>⛰</b><span>{names[r.level-1]}</span></div><div className="routeBody"><small>{r.place}</small><h3>{r.name}</h3><p>{r.desc}</p><div className="metrics"><span>{r.km} km</span><span>↗ {r.up} m</span><span>★ {r.score}</span></div>{profile&&<div className={'compat '+(allowed?'good':'bad')}>{allowed?'● Adecuada para tu perfil':'🔒 Aún no recomendada'}</div>}<button onClick={open}>Ver ruta</button></div></article>}
function Meter({n,v}){return <div className="meter"><span>{n}</span><div><i style={{width:v+'%'}}/></div><b>{v}</b></div>}
function Tool({icon,title,text,click}){return <button className="tool" onClick={click}><b>{icon}</b><span><strong>{title}</strong><small>{text}</small></span></button>}
function Quiz({answers,setAnswers,finish,close}){const q=[['exp','¿Cuánta experiencia real tienes en senderos?',['Casi ninguna','Varias rutas sencillas','Rutas frecuentes','Montaña exigente']],['dist','¿Qué distancia has completado con comodidad?',['< 5 km','5–10 km','10–18 km','> 18 km']],['orient','Si pierdes las marcas, ¿qué sabes hacer?',['No sabría','Volvería sobre mis pasos','Uso track/mapa','Me oriento con mapa y brújula']],['aid','Primeros auxilios en montaña',['Ninguno','Conceptos básicos','Curso realizado','Formación sólida']],['terrain','Terreno técnico y desnivel',['Solo caminos fáciles','Pendientes moderadas','Terreno rocoso','Alta montaña']]];return <div className="overlay"><section className="quiz"><button className="close" onClick={close}>×</button><p className="eyebrow">PERFIL INICIAL</p><h2>No elijas tu nivel. Ayúdanos a conocerlo.</h2><p>Responde con prudencia. Después, tus rutas GPS verificadas irán ajustando el perfil.</p>{q.map(([k,t,opts])=><label key={k}><b>{t}</b><select value={answers[k]} onChange={e=>setAnswers({...answers,[k]:Number(e.target.value)})}>{opts.map((o,i)=><option value={i} key={o}>{o}</option>)}</select></label>)}<button onClick={finish}>Calcular mi perfil</button><small>Este cuestionario no certifica capacidad ni sustituye formación profesional.</small></section></div>}
function Safety({onSOS}){return <div className="safety"><div><p className="eyebrow">SEGURIDAD PRIMERO</p><h2>Prepararse también es senderismo.</h2><p>Offline, orientación, control de ruta, regreso sobre tus pasos y acceso rápido a emergencia.</p></div><button onClick={onSOS}>Abrir SOS</button></div>}
function SOS({loc,close}){return <div className="overlay"><section className="sosModal"><button className="close" onClick={close}>×</button><div className="sosIcon">SOS</div><h2>¿Necesitas ayuda?</h2><p>En una emergencia real llama al <b>112</b>. Cumbre puede mostrar tu posición, pero no garantiza que el 112 la reciba automáticamente.</p>{loc?<div className="coords"><b>Posición GPS</b><span>{loc.lat.toFixed(6)}, {loc.lon.toFixed(6)}</span><small>Precisión aprox. {loc.acc} m</small></div>:<p>Obteniendo ubicación si has concedido permiso…</p>}<a className="call" href="tel:112">☎ Llamar al 112</a>{loc&&<button onClick={()=>navigator.share?.({title:'Ubicación de emergencia',text:`https://maps.google.com/?q=${loc.lat},${loc.lon}`})}>Compartir ubicación</button>}</section></div>}
function Info({title,children,close}){return <div className="overlay"><section className="info"><button className="close" onClick={close}>×</button><h2>{title}</h2>{children}</section></div>}
