'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../lib/supabase';
const H='https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85',L='https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85',P='https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1000&q=85';
export default function Home(){const[menu,setMenu]=useState(false),[route,setRoute]=useState(false),[firstName,setFirstName]=useState('');useEffect(()=>{let active=true;const apply=user=>{if(!active||!user)return;const full=(user.user_metadata?.name||'').trim();setFirstName(full?full.split(/\s+/)[0]:'')};supabase.auth.getUser().then(({data})=>apply(data?.user));const{data:{subscription}}=supabase.auth.onAuthStateChange((_,session)=>apply(session?.user));return()=>{active=false;subscription.unsubscribe()}},[]);return <main className="cumbreApp"><header className="cTop"><button className="hamb" onClick={()=>setMenu(true)}>☰</button><div className="cBrand"><span>△△</span><b>CUMBRE</b></div><button className="bell">♧</button><div className="tagline">DESCUBRE · PREPARA · VIVE · <em>DISFRUTA</em></div></header><section className="cHero" style={{backgroundImage:`linear-gradient(0deg,rgba(0,35,23,.82),rgba(0,20,14,.04) 65%),url(${H})`}}><div className="hello"><h1>¡Hola{firstName?`, ${firstName}`:''}!</h1><p>¿Qué aventura tienes<br/>hoy en mente?</p></div></section><section className="cBody"><div className="cSearch">⌕ <span>Buscar rutas, lugares, experiencias...</span><b>☷</b></div><div className="sectionTitle"><h2>Explora rutas según tu nivel</h2><button>Ver todas</button></div><div className="levelCards"><Level name="Principiante" count="32 rutas" img={H}/><Level name="Intermedio" count="48 rutas" img={L}/><Level name="Experto" count="26 rutas" img={P}/></div><h2 className="blockTitle">Continuar planificación</h2><article className="continue" onClick={()=>setRoute(true)}><img src={L}/><div><b>Ruta del Lago de Sanabria</b><div className="progress"><i/></div><small>♡ 12,4 km　↗ +620 m　◷ 4h 30min</small></div><span>60%</span></article><h2 className="blockTitle">Recomendaciones para ti</h2><article className="recommend"><img src={P}/><div><b>Picos de Europa</b><span>Ideal para ti</span><small>18,7 km · +1.250 m · 6h 15min</small></div></article></section><Bottom/>{menu&&<Menu close={()=>setMenu(false)}/>} {route&&<Route close={()=>setRoute(false)}/>}</main>}
function Level({name,count,img}){return <article style={{backgroundImage:`linear-gradient(0deg,rgba(0,25,17,.72),transparent),url(${img})`}}><span>{name}</span><b>{count}</b></article>}
function Bottom(){return <nav className="bottomNav">{[['⌂','Inicio'],['⌕','Explorar'],['⊙','Grabar'],['♧','Pasaporte'],['♙','Perfil']].map((x,i)=><button className={i===0?'active':''} key={x[1]}><b>{x[0]}</b>{x[1]}</button>)}</nav>}
function Menu({close}){let items=[['⌂','Inicio'],['⌕','Explorar'],['♧','Mis rutas'],['♧','Mapa'],['▣','Pasaporte de Montaña'],['▣','Momentos'],['♙','Experiencias'],['▱','Alojamientos'],['♙','Material'],['♫','Música'],['♢','Seguridad'],['⚙','Configuración'],['?','Ayuda']];return <div className="menuOverlay"><aside className="sideMenu"><div className="menuHead"><div className="cBrand"><span>△△</span><b>CUMBRE</b></div><button onClick={close}>×</button></div>{items.map((x,i)=><button className={i===0?'sel':''} key={x[1]}><b>{x[0]}</b>{x[1]}</button>)}<a href="tel:112" className="menuSOS"><strong>SOS</strong><span>Emergencia 112</span></a></aside></div>}
function Route({close}){return <div className="routeScreen"><div className="routePhoto" style={{backgroundImage:`linear-gradient(0deg,rgba(0,30,20,.9),transparent 60%),url(${L})`}}><button onClick={close}>‹</button><div className="routeActions">♡　⇧</div><div className="routeName"><span>● Adecuada para ti</span><h1>Ruta del Lago de Sanabria</h1><b>Intermedio</b></div></div><section className="routeSheet"><div className="routeStats"><div><strong>12,4 km</strong><small>Distancia</small></div><div><strong>+620 m</strong><small>Desnivel</small></div><div><strong>4h 30min</strong><small>Duración</small></div><div className="score"><strong>94%</strong><small>Adecuada</small></div></div><p>Ruta circular que rodea el Lago de Sanabria, el mayor lago de origen glaciar de la península.</p><b>Ver más　⌄</b><button className="mapBtn">Ver en el mapa</button><h2>Preparada para ti</h2><div className="ready"><div>♧<b>Mapa offline</b><small>✓ Descargado</small></div><div>⌖<b>Track GPS</b><small>✓ Disponible</small></div><div>☀<b>Clima</b><small>18°</small></div></div><button className="startBtn">♙　Iniciar aventura</button></section><Bottom/></div>}
