'use client';

import {useEffect,useRef,useState} from 'react';

export default function RecoveryRouteMap({track,position,target,bearing}){
 const nodeRef=useRef(null),mapRef=useRef(null),userRef=useRef(null),returnRef=useRef(null),[tileError,setTileError]=useState(false),[routing,setRouting]=useState('Calculando retorno por caminos…');
 useEffect(()=>{let active=true;async function mount(){const L=(await import('leaflet')).default;if(!active||!nodeRef.current)return;const route=track.points.map(point=>[point.lat,point.lon]),map=L.map(nodeRef.current,{zoomControl:false,attributionControl:true});mapRef.current=map;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).on('tileerror',()=>setTileError(true)).addTo(map);L.polyline(route,{color:'#053e2c',weight:11,opacity:.72}).addTo(map);L.polyline(route,{color:'#73d342',weight:6}).addTo(map);L.circleMarker([target.lat,target.lon],{radius:8,color:'#fff',weight:3,fillColor:'#ef302b',fillOpacity:1}).addTo(map);const icon=L.divIcon({className:'hikerArrowIcon recoveryArrow',html:`<span style="transform:rotate(${bearing}deg)">▲</span>`,iconSize:[46,46],iconAnchor:[23,23]});userRef.current=L.marker([position.lat,position.lon],{icon,zIndexOffset:1000}).addTo(map);map.fitBounds(L.latLngBounds([...route,[position.lat,position.lon],[target.lat,target.lon]]),{padding:[45,45]});L.control.zoom({position:'bottomright'}).addTo(map)}mount();return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[track.id]);
 useEffect(()=>{const map=mapRef.current;if(!map||!userRef.current)return;import('leaflet').then(module=>{const L=module.default,icon=L.divIcon({className:'hikerArrowIcon recoveryArrow',html:`<span style="transform:rotate(${bearing}deg)">▲</span>`,iconSize:[46,46],iconAnchor:[23,23]});userRef.current.setLatLng([position.lat,position.lon]).setIcon(icon);map.panTo([position.lat,position.lon],{animate:true})})},[position.lat,position.lon,bearing]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(async()=>{try{const response=await fetch('/api/navigation/return',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:position,to:target}),signal:controller.signal}),body=await response.json();if(!response.ok||!Array.isArray(body.points))throw new Error(body.error);const L=(await import('leaflet')).default,map=mapRef.current;if(!map)return;returnRef.current?.remove();returnRef.current=L.polyline(body.points.map(point=>[point.lat,point.lon]),{color:'#ef302b',weight:7}).addTo(map);setRouting(`${Math.round(body.distanceM)} m por caminos`) }catch(error){if(!controller.signal.aborted){returnRef.current?.remove();returnRef.current=null;setRouting(error instanceof Error?error.message:'No se ha encontrado un retorno seguro.')}}},1200);return()=>{clearTimeout(timer);controller.abort()}},[position.lat,position.lon,target.lat,target.lon]);
 return <div className="recoveryCartography"><div ref={nodeRef} className="recoveryMapCanvas"/>{tileError&&<div className="recoveryOffline">Sin fondo cartográfico · GPS y sendero siguen visibles</div>}<div className="recoveryLegend"><span><i className="legendGreen"/>Sendero</span><span><i className="legendRed"/>Retorno por caminos</span><span><i className="legendBlue"/>Tu posición</span></div><div className="recoveryRoutingStatus">{routing}</div></div>
}
