'use client';

import { useEffect, useRef, useState } from 'react';

export default function RecoveryRouteMap({track,position,target,bearing}){
  const nodeRef=useRef(null),mapRef=useRef(null),userRef=useRef(null),returnRef=useRef(null),[tileError,setTileError]=useState(false);
  useEffect(()=>{let active=true;async function mount(){const L=(await import('leaflet')).default;if(!active||!nodeRef.current)return;const route=track.points.map(p=>[p.lat,p.lon]),map=L.map(nodeRef.current,{zoomControl:false,attributionControl:true});mapRef.current=map;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).on('tileerror',()=>setTileError(true)).addTo(map);L.polyline(route,{color:'#053e2c',weight:11,opacity:.72}).addTo(map);L.polyline(route,{color:'#73d342',weight:6}).addTo(map);L.circleMarker([target.lat,target.lon],{radius:8,color:'#fff',weight:3,fillColor:'#ef302b',fillOpacity:1}).addTo(map);returnRef.current=L.polyline([[position.lat,position.lon],[target.lat,target.lon]],{color:'#ef302b',weight:7,dashArray:'12 8'}).addTo(map);const icon=L.divIcon({className:'hikerArrowIcon recoveryArrow',html:`<span style="transform:rotate(${bearing}deg)">▲</span>`,iconSize:[46,46],iconAnchor:[23,23]});userRef.current=L.marker([position.lat,position.lon],{icon,zIndexOffset:1000}).addTo(map);map.fitBounds(L.latLngBounds([...route,[position.lat,position.lon],[target.lat,target.lon]]),{padding:[45,45]});L.control.zoom({position:'bottomright'}).addTo(map)}mount();return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[track.id]);
  useEffect(()=>{const map=mapRef.current;if(!map||!userRef.current)return;import('leaflet').then(module=>{const L=module.default,icon=L.divIcon({className:'hikerArrowIcon recoveryArrow',html:`<span style="transform:rotate(${bearing}deg)">▲</span>`,iconSize:[46,46],iconAnchor:[23,23]});userRef.current.setLatLng([position.lat,position.lon]).setIcon(icon);returnRef.current?.setLatLngs([[position.lat,position.lon],[target.lat,target.lon]]);map.panTo([position.lat,position.lon],{animate:true})})},[position.lat,position.lon,bearing,target.lat,target.lon]);
  return <div className="recoveryCartography"><div ref={nodeRef} className="recoveryMapCanvas"/>{tileError&&<div className="recoveryOffline">Sin fondo cartográfico · GPS y trazados siguen activos</div>}<div className="recoveryLegend"><span><i className="legendGreen"/>Sendero</span><span><i className="legendRed"/>Vuelta al camino</span><span><i className="legendBlue"/>Tu posición</span></div></div>
}
