'use client';
import {useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import './report-user.css';

const CATEGORIES=[
 ['harassment','Acoso o falta de respeto'],
 ['racism','Racismo'],
 ['xenophobia','Xenofobia'],
 ['threats','Amenazas o intimidación'],
 ['sexual','Contenido o conducta sexual inapropiada'],
 ['impersonation','Suplantación de identidad'],
 ['spam','Spam o fraude'],
 ['other','Otro comportamiento indecoroso']
];

export default function ReportUserModal({user,reported,close}){
 const[name,setName]=useState((user.user_metadata?.name||user.user_metadata?.full_name||'').trim()),[email,setEmail]=useState(user.email||''),[description,setDescription]=useState(''),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false),[evidenceWarning,setEvidenceWarning]=useState('');
 const words=useMemo(()=>description.trim()?description.trim().split(/\s+/).length:0,[description]);
 function chooseFiles(event){const selected=[...event.target.files];if(selected.length>5)return setError('Puedes adjuntar un máximo de 5 imágenes.');if(selected.some(file=>!['image/jpeg','image/png','image/webp'].includes(file.type)))return setError('Solo se admiten imágenes JPG, PNG o WebP.');if(selected.some(file=>file.size>5*1024*1024))return setError('Cada imagen debe ocupar como máximo 5 MB.');setError('');setFiles(selected)}
 async function submit(event){event.preventDefault();if(words>200)return setError('La explicación no puede superar las 200 palabras.');setBusy(true);setError('');const form=new FormData(event.currentTarget),category=form.get('category');const{data:reportId,error:reportError}=await supabase.rpc('submit_social_report',{p_reported_user:reported.user_id,p_reporter_name:name.trim(),p_reporter_email:email.trim(),p_category:category,p_description:description.trim()});if(reportError){setBusy(false);return setError(reportError.message?.includes('duplicate_report')?'Ya has enviado una denuncia reciente sobre este usuario.':'No hemos podido registrar la denuncia. Inténtalo de nuevo.')}const paths=[];for(const file of files){const extension=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${user.id}/${reportId}/${crypto.randomUUID?.()||Date.now()}.${extension}`;const{error:uploadError}=await supabase.storage.from('social-report-evidence').upload(path,file,{contentType:file.type,upsert:false});if(!uploadError)paths.push(path)}if(paths.length){await supabase.rpc('attach_social_report_evidence',{p_report_id:reportId,p_paths:paths})}if(paths.length!==files.length)setEvidenceWarning('La denuncia se registró, pero alguna imagen no pudo adjuntarse.');setBusy(false);setSent(true)}
 if(sent)return <div className="reportOverlay" role="dialog" aria-modal="true"><section className="reportSuccess"><span>✓</span><h2>Denuncia recibida</h2><p>El equipo de Encúmbrate revisará la información y las pruebas. No se sancionará a nadie únicamente por el número de denuncias.</p>{evidenceWarning&&<small>{evidenceWarning}</small>}<button onClick={close}>Cerrar</button></section></div>;
 return <div className="reportOverlay" role="dialog" aria-modal="true" aria-label="Denunciar usuario"><form className="reportForm" onSubmit={submit}><header><div><small>SEGURIDAD DE LA COMUNIDAD</small><h2>Denunciar a @{reported.alias}</h2></div><button type="button" onClick={close} aria-label="Cerrar">×</button></header><p className="reportNotice">Describe hechos concretos. Las denuncias falsas o malintencionadas también incumplen las normas de convivencia.</p><label>Tu nombre<input required minLength="2" maxLength="80" value={name} onChange={event=>setName(event.target.value)} placeholder="Nombre y apellidos"/></label><label>Tu correo<input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="correo@ejemplo.com"/></label><label>Motivo<select required name="category" defaultValue=""><option value="" disabled>Selecciona una categoría</option>{CATEGORIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>¿Qué ha ocurrido?<textarea required minLength="20" maxLength="1400" value={description} onChange={event=>setDescription(event.target.value)} placeholder="Explica qué ocurrió, cuándo y dónde. Evita incluir datos personales innecesarios."/>{<small className={words>200?'over':''}>{words} de 200 palabras</small>}</label><label className="reportFiles"><b>Añadir capturas o fotografías</b><span>Hasta 5 imágenes JPG, PNG o WebP · máximo 5 MB cada una</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={chooseFiles}/>{files.length>0&&<em>{files.length} archivo{files.length===1?'':'s'} seleccionado{files.length===1?'':'s'}</em>}</label><label className="reportConfirm"><input required type="checkbox"/><span>Confirmo que la información es veraz y autorizo a Encúmbrate a revisar estas pruebas para moderar la comunidad.</span></label>{error&&<p className="reportError">{error}</p>}<button className="reportSubmit" disabled={busy||words>200}>{busy?'Enviando denuncia…':'Enviar denuncia'}</button></form></div>
}
