'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';

const FALLBACK_POSITION={lat:38.3452,lon:-0.4815};
const ROUTE_DATA_VERSION='2026-08-26-photos-metrics-v1';
const LEVEL_LABELS={principiante:'Principiante',intermedio:'Intermedio',experto:'Experto'};
const TERRITORIES={
 'Andalucía':['Almería','Cádiz','Córdoba','Granada','Huelva','Jaén','Málaga','Sevilla'],
 'Aragón':['Huesca','Teruel','Zaragoza'],'Principado de Asturias':['Asturias'],'Illes Balears':['Illes Balears'],
 'Canarias':['Las Palmas','Santa Cruz de Tenerife'],'Cantabria':['Cantabria'],
 'Castilla-La Mancha':['Albacete','Ciudad Real','Cuenca','Guadalajara','Toledo'],
 'Castilla y León':['Ávila','Burgos','León','Palencia','Salamanca','Segovia','Soria','Valladolid','Zamora'],
 'Cataluña':['Barcelona','Girona','Lleida','Tarragona'],'Comunidad Valenciana':['Alicante','Castellón','Valencia'],
 'Extremadura':['Badajoz','Cáceres'],'Galicia':['A Coruña','Lugo','Ourense','Pontevedra'],'La Rioja':['La Rioja'],
 'Comunidad de Madrid':['Madrid'],'Región de Murcia':['Murcia'],'Comunidad Foral de Navarra':['Navarra'],
 'País Vasco':['Álava','Bizkaia','Gipuzkoa'],'Ceuta':['Ceuta'],'Melilla':['Melilla']
};
const levelClass=level=>`routeLevel routeLevel-${level}`;
const value=(number,suffix)=>Number.isFinite(number)?`${number.toLocaleString('es-ES',{maximumFractionDigits:1})}${suffix}`:'No publicado';
function haversine(a,b){const rad=v=>v*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}

const routePhotoCache=new Map(),routeProfileCache=new Map();
function useRoutePhoto(route,enabled=true){const initialItem={src:route.image||'',specific:Boolean(route.imageIsSpecific),trace:false,sourceUrl:route.imageSourceUrl||route.sourceUrl,credit:route.imageAttribution||'',license:route.imageLicense||''},initial={...initialItem,gallery:route.imageIsSpecific?[initialItem,...(route.imageGallery||[])]:[]};const[photo,setPhoto]=useState(()=>routePhotoCache.get(route.id)||initial);useEffect(()=>{let active=true;if(!enabled||route.imageIsSpecific)return()=>{active=false};const cached=routePhotoCache.get(route.id);if(cached){setPhoto(cached);return()=>{active=false}}const params=new URLSearchParams({name:route.name,ref:route.ref||'',wikipedia:route.wikipedia||'',wikidata:route.wikidata||'',category:route.commonsCategory||'',lat:String(route.lat),lon:String(route.lon)});fetch(`/api/routes/image?${params}`).then(response=>response.json()).then(data=>{const gallery=(data.gallery||[]).map(item=>({...item,specific:true}));const trace={src:`/api/routes/trace?id=${encodeURIComponent(route.id)}`,specific:false,trace:true,sourceUrl:route.sourceUrl,credit:'Trazado público de OpenStreetMap',license:'© OpenStreetMap contributors',gallery:[]};const resolved=data.found?{src:data.src,specific:true,trace:false,sourceUrl:data.sourceUrl,credit:data.credit,license:data.license,gallery}:trace;routePhotoCache.set(route.id,resolved);if(active)setPhoto(resolved)}).catch(()=>{const trace={src:`/api/routes/trace?id=${encodeURIComponent(route.id)}`,specific:false,trace:true,sourceUrl:route.sourceUrl,credit:'Trazado público de OpenStreetMap',license:'© OpenStreetMap contributors',gallery:[]};routePhotoCache.set(route.id,trace);if(active)setPhoto(trace)});return()=>{active=false}},[route.id,route.imageIsSpecific,enabled]);return photo}
function useRouteProfile(route,enabled=true){const complete=Number.isFinite(route.distanceKm)&&Number.isFinite(route.ascentM)&&Number.isFinite(route.maxAltitudeM)&&Number.isFinite(route.minAltitudeM)&&Boolean(route.duration);const[profile,setProfile]=useState(()=>routeProfileCache.get(route.id)||null);useEffect(()=>{let active=true;if(!enabled||complete||routeProfileCache.has(route.id))return()=>{active=false};fetch(`/api/routes/profile?id=${encodeURIComponent(route.id)}`).then(response=>response.json()).then(data=>{if(!data.found)return;routeProfileCache.set(route.id,data);if(active)setProfile(data)}).catch(()=>{});return()=>{active=false}},[route.id,enabled,complete]);return profile}
function enrichedRoute(route,profile){if(!profile)return route;return{...route,distanceKm:route.distanceKm??profile.distanceKm,ascentM:route.ascentM??profile.ascentM,maxAltitudeM:route.maxAltitudeM??profile.maxAltitudeM,minAltitudeM:route.minAltitudeM??profile.minAltitudeM,duration:route.duration||profile.duration,metricsSource:route.metricsSource||profile.source}}

export default function RouteCatalog(){
 const[routes,setRoutes]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[catalogOpen,setCatalogOpen]=useState(false),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[placeQuery,setPlaceQuery]=useState(''),[catalogLabel,setCatalogLabel]=useState(''),[placeLoading,setPlaceLoading]=useState(false),[placeError,setPlaceError]=useState(''),[level,setLevel]=useState('todas'),[usingLocation,setUsingLocation]=useState(false),[completed,setCompleted]=useState({}),[historyOpen,setHistoryOpen]=useState(false);
 useEffect(()=>{let active=true;const load=position=>{const params=new URLSearchParams({lat:String(position.lat),lon:String(position.lon),radius:'20000',v:ROUTE_DATA_VERSION});fetch(`/api/routes?${params}`,{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'No se ha podido cargar el catálogo.');if(active){setRoutes(body.routes||[]);setLoading(false)}}).catch(err=>{if(active){setError(err.message);setLoading(false)}})};if(!navigator.geolocation)return load(FALLBACK_POSITION);navigator.geolocation.getCurrentPosition(({coords})=>{setUsingLocation(true);load({lat:coords.latitude,lon:coords.longitude})},()=>load(FALLBACK_POSITION),{enableHighAccuracy:false,timeout:7000,maximumAge:300000});return()=>{active=false}},[]);
 useEffect(()=>{const open=()=>setCatalogOpen(true),history=()=>setHistoryOpen(true);window.addEventListener('encumbrate:open-routes',open);window.addEventListener('encumbrate:open-route-history',history);return()=>{window.removeEventListener('encumbrate:open-routes',open);window.removeEventListener('encumbrate:open-route-history',history)}},[]);
 useEffect(()=>{loadCompleted()},[]);
 async function loadCompleted(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from('route_activities').select('id,external_route_key,route_name,route_difficulty,status,distance_km,duration_seconds,trophy_earned,ended_at').eq('user_id',user.id).order('started_at',{ascending:false});const map={};for(const activity of data||[])if(activity.external_route_key&&!map[activity.external_route_key])map[activity.external_route_key]=activity;setCompleted(map)}
 async function loadPlace(place,scope='place'){const clean=place.trim();if(!clean)return setPlaceError('Escribe una localidad o elige una provincia.');setPlaceLoading(true);setPlaceError('');try{const params=new URLSearchParams({place:clean,radius:'20000',scope,v:ROUTE_DATA_VERSION});const response=await fetch(`/api/routes?${params}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'No se ha podido buscar esa zona.');setRoutes(body.routes||[]);setCatalogLabel(body.searchLabel||clean);setUsingLocation(false);setQuery('');if(!(body.routes||[]).length)setPlaceError('No hay rutas públicas catalogadas cerca de esa zona.')}catch(error){setPlaceError(error.message||'No se ha podido buscar esa zona.')}finally{setPlaceLoading(false)}}
 async function searchPlace(event){event?.preventDefault();await loadPlace(placeQuery)}
 const filtered=useMemo(()=>routes.filter(route=>(level==='todas'||route.level===level)&&(!query.trim()||`${route.name} ${route.ref}`.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es')))),[routes,query,level]);
 const nearest=routes.slice(0,3);
 return <>
  <button className="cSearch routeSearchTrigger" onClick={()=>setCatalogOpen(true)} aria-label="Buscar entre todas las rutas"><span className="searchIcon">⌕</span><span>Buscar rutas por nombre…</span><b>☷</b></button>
  <div className="sectionTitle"><div><h2>{catalogLabel?`Rutas cerca de ${catalogLabel.split(',')[0]}`:'Rutas cerca de ti'}</h2><small>{catalogLabel?'Zona elegida en el buscador':usingLocation?'Ordenadas desde tu ubicación':'Mostrando Alicante como ubicación inicial'}</small></div><button onClick={()=>setCatalogOpen(true)}>Ver todas</button></div>
  {loading?<div className="routesState"><i/>Buscando rutas públicas cercanas…</div>:error?<div className="routesState routesError">{error}</div>:nearest.length?<div className="nearbyRoutes">{nearest.map(route=><RouteCard key={route.id} route={route} activity={completed[route.id]} onClick={shown=>setSelected(shown)}/>)}</div>:<div className="routesState">No hay rutas públicas catalogadas en este radio.</div>}
  {catalogOpen&&<RouteDirectory routes={filtered} completed={completed} query={query} setQuery={setQuery} placeQuery={placeQuery} setPlaceQuery={setPlaceQuery} searchPlace={searchPlace} loadPlace={loadPlace} placeLoading={placeLoading} placeError={placeError} catalogLabel={catalogLabel} level={level} setLevel={setLevel} close={()=>setCatalogOpen(false)} history={()=>{setCatalogOpen(false);setHistoryOpen(true)}} select={route=>{setCatalogOpen(false);setSelected(route)}}/>}
  {historyOpen&&<RouteHistory activities={Object.values(completed)} close={()=>setHistoryOpen(false)}/>}
  {selected&&<RouteDetail route={selected} activity={completed[selected.id]} close={()=>setSelected(null)} onSaved={loadCompleted}/>}
 </>
}

function RouteCard({route,onClick,activity}){
 const cardRef=useRef(null),[visible,setVisible]=useState(false),photo=useRoutePhoto(route,visible),profile=useRouteProfile(route,visible),shown=enrichedRoute(route,profile);
 useEffect(()=>{const node=cardRef.current;if(!node)return;if(!('IntersectionObserver' in window)){setVisible(true);return}const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){setVisible(true);observer.disconnect()}},{rootMargin:'240px'});observer.observe(node);return()=>observer.disconnect()},[]);
 return <button ref={cardRef} className={`nearbyRoute ${activity?.trophy_earned?'routeCompleted':''}`} onClick={()=>onClick(shown)}><div className="routeCardPhoto">{photo.src?<img className={photo.trace?'routeTraceImage':''} src={photo.src} alt={photo.trace?`Trazado de ${route.name}`:`Imagen verificada de ${route.name}`} loading="lazy" onError={event=>{event.currentTarget.hidden=true;event.currentTarget.nextElementSibling?.removeAttribute('hidden')}}/>:null}<div className="routePhotoMissing" hidden={Boolean(photo.src)}><span>⌖</span><small>Preparando<br/>trazado…</small></div>{activity?.trophy_earned&&<span className="goldTrophy" aria-label="Ruta completada">🏆</span>}</div><div className="nearbyRouteBody"><div><span className={activity?.trophy_earned?'completedLabel':levelClass(route.level)}>{activity?.trophy_earned?'COMPLETADA':LEVEL_LABELS[route.level]}</span><small>{route.nearbyKm.toLocaleString('es-ES',{maximumFractionDigits:1})} km de ti</small></div><strong>{route.name}</strong>{route.ref&&<em>{route.ref}</em>}<p><b>{value(shown.distanceKm,' km')}</b><span>↗ {value(shown.ascentM,' m')}</span><span>△ {value(shown.maxAltitudeM,' m')}</span></p>{visible&&!shown.distanceKm&&<small className="routeMetricsLoading">Calculando ficha…</small>}</div><span className="routeChevron">›</span></button>
}

function RouteDirectory({routes,completed,query,setQuery,placeQuery,setPlaceQuery,searchPlace,loadPlace,placeLoading,placeError,catalogLabel,level,setLevel,close,select,history}){const[community,setCommunity]=useState(''),[province,setProvince]=useState('');function chooseCommunity(event){setCommunity(event.target.value);setProvince('')}function chooseProvince(event){const value=event.target.value;setProvince(value);if(value){setPlaceQuery(value);loadPlace(`${value}, España`,'province')}}return <div className="routeDirectory"><header><button onClick={close}>‹</button><div><small>EXPERIENCIAS</small><h1>Buscador de rutas</h1></div><button className="historyButton" onClick={history} aria-label="Abrir mis rutas">🏆</button></header><div className="routeDirectoryControls"><div className="territorySelectors"><select value={community} onChange={chooseCommunity} aria-label="Elegir comunidad autónoma"><option value="">Comunidad autónoma</option>{Object.keys(TERRITORIES).map(name=><option key={name} value={name}>{name}</option>)}</select><select value={province} onChange={chooseProvince} disabled={!community||placeLoading} aria-label="Elegir provincia"><option value="">Provincia</option>{(TERRITORIES[community]||[]).map(name=><option key={name} value={name}>{name}</option>)}</select></div><form className="placeSearch" onSubmit={searchPlace}><label><span>⌖</span><input autoFocus value={placeQuery} onChange={event=>setPlaceQuery(event.target.value)} placeholder="O escribe: Bilbao, Picos de Europa…"/></label><button disabled={placeLoading}>{placeLoading?'Buscando…':'Buscar zona'}</button></form>{placeError&&<small className="placeSearchError">{placeError}</small>}<p className="searchArea">{catalogLabel?`Buscando alrededor de ${catalogLabel}`:'Elige comunidad y provincia, o busca cualquier localidad de España.'}</p><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filtrar por nombre de ruta"/></label><select value={level} onChange={event=>setLevel(event.target.value)} aria-label="Filtrar por nivel"><option value="todas">Todos los niveles</option><option value="principiante">Principiante</option><option value="intermedio">Intermedio</option><option value="experto">Experto</option></select></div><p className="routeCount">{routes.length} rutas encontradas en esta zona</p><div className="routeDirectoryList">{routes.map(route=><RouteCard key={route.id} route={route} activity={completed[route.id]} onClick={select}/>)}{!routes.length&&<div className="routesState">No hay coincidencias. Prueba otra provincia, localidad, nombre o nivel.</div>}</div><footer>Busca cualquier comunidad, provincia o localidad de España · Datos públicos · © OpenStreetMap contributors.</footer></div>}

function RouteDetail({route,activity,close,onSaved}){
 const photo=useRoutePhoto(route,true),profile=useRouteProfile(route,true),shown=enrichedRoute(route,profile);
 return <div className="routeScreen catalogRouteDetail"><div className={`routePhoto ${photo.src?'':'routePhotoNoImage'}`} style={photo.src?{backgroundImage:`linear-gradient(0deg,rgba(0,30,20,.92),transparent 62%),url(${photo.src})`}:undefined}><button onClick={close} aria-label="Volver">‹</button>{!photo.src&&<div className="detailPhotoMissing">⌖ Preparando trazado público…</div>}{activity?.trophy_earned&&<div className="detailTrophy">🏆 <b>COMPLETADA</b></div>}<div className="routeName"><span>{route.nearbyKm.toLocaleString('es-ES',{maximumFractionDigits:1})} km desde tu ubicación</span><h1>{route.name}</h1><b className={levelClass(route.level)}>{LEVEL_LABELS[route.level]}</b></div></div><section className="routeSheet"><div className="routeStats"><div><strong>{value(shown.distanceKm,' km')}</strong><small>Distancia</small></div><div><strong>{value(shown.ascentM,' m')}</strong><small>Desnivel +</small></div><div><strong>{value(shown.maxAltitudeM,' m')}</strong><small>Altitud máx.</small></div><div><strong>{shown.duration||'Calculando…'}</strong><small>Duración</small></div></div>{shown.metricsSource&&<p className="routeMetricsSource">Datos: {shown.metricsSource}</p>}{photo.credit&&<p className="routePhotoCredit">{photo.trace?'Trazado':'Foto'}: <a href={photo.sourceUrl} target="_blank" rel="noopener noreferrer">{photo.credit}</a>{photo.license?` · ${photo.license}`:''}</p>}<p>{route.description}</p><div className="routeFacts"><div><small>Nivel orientativo</small><strong>{LEVEL_LABELS[route.level]}</strong></div><div><small>Recorrido</small><strong>{shown.routeType}</strong></div><div><small>Altitud mínima</small><strong>{value(shown.minAltitudeM,' m')}</strong></div><div><small>Red senderista</small><strong>{route.network||'No publicada'}</strong></div></div><RouteAccess route={route}/><RouteGallery photos={photo.gallery||[]} routeName={route.name}/><GpsRecorder route={route} previous={activity} onSaved={onSaved}/>{photo.trace&&<p className="routePhotoNotice">No existe todavía una fotografía pública inequívoca de esta ruta. Mostramos su trazado real y lo sustituiremos cuando exista una imagen verificada o aportada por la comunidad.</p>}<a className="mapBtn routeSource" href={route.officialUrl||route.sourceUrl} target="_blank" rel="noopener noreferrer">Consultar fuente pública ↗</a><p className="routeSafety">Comprueba señalización, meteorología y avisos oficiales antes de salir. La copa acredita el registro GPS dentro de Encúmbrate; no sustituye una homologación oficial.</p></section></div>
}

function RouteGallery({photos,routeName}){if(!photos.length)return null;return <section className="routeGallery"><h2>Imágenes del sendero</h2><div>{photos.map((photo,index)=><a key={`${photo.src}-${index}`} href={photo.sourceUrl} target="_blank" rel="noopener noreferrer"><img src={photo.src} alt={`${routeName}, imagen ${index+1}`} loading="lazy"/><small>{photo.credit||'Ver origen'}</small></a>)}</div></section>}

function RouteAccess({route}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;const params=new URLSearchParams({id:route.id,lat:String(route.lat),lon:String(route.lon)});setLoading(true);setError('');fetch(`/api/routes/access?${params}`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'No se ha podido calcular el acceso.');if(active)setData(body)}).catch(error=>{if(active)setError(error.message||'No se ha podido calcular el acceso.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[route.id,route.lat,route.lon]);
 function armTracking(trailhead){const payload={routeId:route.id,trailhead:trailhead||{lat:route.lat,lon:route.lon},armedAt:new Date().toISOString()};localStorage.setItem('encumbrate:armed-route',JSON.stringify(payload));window.dispatchEvent(new CustomEvent('encumbrate:route-armed',{detail:payload}))}
 const fallbackWalking=`https://www.google.com/maps/dir/?api=1&destination=${route.lat},${route.lon}&travelmode=walking&dir_action=navigate`;
 return <section className="routeAccess"><h2>Cómo llegar al sendero</h2>{loading?<div className="routeAccessLoading"><i/>Buscando el aparcamiento público más próximo…</div>:error?<><p className="routeAccessWarning">{error}</p><a className="walkingOnlyButton" href={fallbackWalking} onClick={()=>armTracking()} target="_blank" rel="noopener noreferrer">Abrir ubicación aproximada en Google Maps</a></>:data?.foundParking?<><div className="parkingSummary"><span>🅿</span><div><strong>{data.parking.name}</strong><small>A unos {data.walkingDistanceKm.toLocaleString('es-ES',{maximumFractionDigits:1})} km del punto de acceso calculado</small></div></div><div className="routeAccessSteps"><a href={data.drivingUrl} onClick={()=>armTracking(data.trailhead)} target="_blank" rel="noopener noreferrer"><b>1</b><span><strong>Ir en coche</strong><small>Google Maps hasta el aparcamiento</small></span></a><a href={data.walkingUrl} onClick={()=>armTracking(data.trailhead)} target="_blank" rel="noopener noreferrer"><b>2</b><span><strong>Continuar a pie</strong><small>Del aparcamiento al sendero</small></span></a></div><p className="routeAccessNote">{data.note} Al volver a Encúmbrate junto al sendero, el registro GPS comenzará automáticamente.</p></>:<><p className="routeAccessWarning">{data?.note}</p><a className="walkingOnlyButton" href={data?.walkingUrl} onClick={()=>armTracking(data?.trailhead)} target="_blank" rel="noopener noreferrer">Abrir acceso a pie en Google Maps</a></>}<RouteConditions data={data}/></section>
}

function RouteConditions({data}){if(!data?.petPolicy)return null;const groups=[['Refugios',data.nearby?.shelters],['Hostales y cabañas',data.nearby?.lodging],['Bares y restaurantes',data.nearby?.food],['Centros médicos',data.nearby?.medical],['Tiendas',data.nearby?.shops]];return <div className="routeConditions"><h2>Servicios y condiciones</h2><div className={`petCondition petCondition-${data.petPolicy.status}`}><span>🐾</span><div><strong>{data.petPolicy.label}</strong><small>{data.petPolicy.detail}</small></div></div><div className={`campCondition campCondition-${data.campingPolicy?.status||'unknown'}`}><span>⛺</span><div><strong>{data.campingPolicy?.label}</strong><small>{data.campingPolicy?.detail}</small></div></div>{data.nearby?.camping?.length>0&&<NearbyPlaces title="Campings" items={data.nearby.camping}/>} {groups.map(([title,items])=><NearbyPlaces key={title} title={title} items={items||[]}/>)}</div>}
function NearbyPlaces({title,items}){return <div className="nearbyPlaces"><strong>{title}</strong>{items.length?<div>{items.map((item,index)=><a key={`${title}-${index}`} href={item.mapsUrl} target="_blank" rel="noopener noreferrer"><span>{item.name}</span><small>{item.distanceKm.toLocaleString('es-ES',{maximumFractionDigits:1})} km de la ruta ↗</small></a>)}</div>:<small>No hay información pública cercana en OpenStreetMap.</small>}</div>}

function GpsRecorder({route,previous,onSaved}){const[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[stats,setStats]=useState({points:0,distance:0}),[armed,setArmed]=useState(null);const watchRef=useRef(null),activityRef=useRef(null),pointsRef=useRef([]),sequenceRef=useRef(0),startingRef=useRef(false),arrivalCheckingRef=useRef(false);
 useEffect(()=>()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current)},[]);
 useEffect(()=>{function sync(event){let payload=event?.detail;try{payload=payload||JSON.parse(localStorage.getItem('encumbrate:armed-route')||'null')}catch{payload=null}setArmed(payload?.routeId===route.id?payload:null)}sync();window.addEventListener('encumbrate:route-armed',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('encumbrate:route-armed',sync);window.removeEventListener('storage',sync)}},[route.id]);
 useEffect(()=>{if(!armed||recording||busy||previous?.trophy_earned||!navigator.geolocation)return;let active=true;function checkArrival(){if(!active||document.visibilityState==='hidden'||arrivalCheckingRef.current||startingRef.current)return;arrivalCheckingRef.current=true;navigator.geolocation.getCurrentPosition(position=>{arrivalCheckingRef.current=false;if(!active)return;const distance=haversine({lat:position.coords.latitude,lon:position.coords.longitude},armed.trailhead);if(distance<=.15){setMessage('Has llegado al sendero. Iniciando el registro GPS automáticamente…');start()}else setMessage(`Inicio automático preparado · estás a ${distance.toLocaleString('es-ES',{maximumFractionDigits:1})} km del acceso`)},error=>{arrivalCheckingRef.current=false;if(!active)return;setMessage(error.code===1?'Necesitamos permiso de ubicación para detectar tu llegada al sendero.':'Esperando una señal GPS válida para detectar tu llegada.');if(error.code===1){localStorage.removeItem('encumbrate:armed-route');setArmed(null)}},{enableHighAccuracy:true,maximumAge:10000,timeout:15000})}checkArrival();const interval=setInterval(checkArrival,15000),onVisible=()=>{if(document.visibilityState==='visible')checkArrival()};document.addEventListener('visibilitychange',onVisible);return()=>{active=false;clearInterval(interval);document.removeEventListener('visibilitychange',onVisible)}},[armed,recording,busy,route.id,previous?.trophy_earned]);
 async function start(){if(startingRef.current||recording)return;startingRef.current=true;setBusy(true);setMessage('Preparando el GPS…');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Inicia sesión para guardar la ruta.');if(!navigator.geolocation)throw new Error('Este dispositivo no ofrece ubicación GPS.');const{data:activity,error}=await supabase.from('route_activities').insert({user_id:user.id,external_route_key:route.id,route_name:route.name,route_difficulty:route.level,planned_distance_km:route.distanceKm||null,status:'recording'}).select('id,started_at').single();if(error)throw error;activityRef.current={...activity,userId:user.id};pointsRef.current=[];sequenceRef.current=0;watchRef.current=navigator.geolocation.watchPosition(position=>savePoint(position,user.id,activity.id),gpsError=>setMessage(gpsError.code===1?'Activa el permiso de ubicación para grabar la ruta.':'Se ha perdido temporalmente la señal GPS.'),{enableHighAccuracy:true,maximumAge:3000,timeout:15000});localStorage.removeItem('encumbrate:armed-route');setArmed(null);setRecording(true);setMessage('Grabando recorrido GPS. Mantén Encúmbrate abierta.')}catch(error){localStorage.removeItem('encumbrate:armed-route');setArmed(null);setMessage(error.message||'No hemos podido iniciar la grabación.')}finally{startingRef.current=false;setBusy(false)}}
 async function savePoint(position,userId,activityId){const point={lat:position.coords.latitude,lon:position.coords.longitude,altitude:position.coords.altitude,accuracy:position.coords.accuracy,at:new Date(position.timestamp).toISOString()};if(point.accuracy>100)return;const previous=pointsRef.current.at(-1);if(previous&&haversine(previous,point)<.005)return;pointsRef.current.push(point);sequenceRef.current+=1;let distance=0;for(let i=1;i<pointsRef.current.length;i++)distance+=haversine(pointsRef.current[i-1],pointsRef.current[i]);setStats({points:pointsRef.current.length,distance});const{error}=await supabase.from('activity_gps_points').insert({activity_id:activityId,user_id:userId,sequence_number:sequenceRef.current,recorded_at:point.at,latitude:point.lat,longitude:point.lon,accuracy_m:point.accuracy,altitude_m:point.altitude});if(error)setMessage('Seguimos grabando, pero un punto GPS no ha podido guardarse.')}
 async function finish(){setBusy(true);if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;const{data,error}=await supabase.rpc('finalize_external_route_activity',{p_activity_id:activityRef.current.id});setRecording(false);setBusy(false);if(error)return setMessage('La grabación terminó, pero no hemos podido guardar el resultado.');setMessage(data?.trophy_earned?'¡Ruta completada! Has conseguido la copa dorada.':'Ruta guardada como incompleta. Podrás volver a intentarla.');onSaved?.()}
 return <section className="gpsRecorder">{previous?.trophy_earned?<div className="gpsCompleted"><span>🏆</span><div><strong>Ruta completada</strong><small>{Number(previous.distance_km||0).toLocaleString('es-ES',{maximumFractionDigits:1})} km registrados</small></div></div>:<><h2>Registro GPS automático</h2><p>Al abrir las indicaciones, Encúmbrate prepara esta ruta. Cuando vuelvas a la aplicación y estés a menos de 150 m del sendero, comenzará a guardar tus pasos automáticamente.</p>{armed&&!recording&&<div className="gpsAutoArmed"><b>⌖ DETECCIÓN PREPARADA</b><span>Te avisaremos al llegar al sendero</span></div>}{recording&&<div className="gpsLive"><b>● EN GRABACIÓN</b><span>{stats.points} puntos</span><span>{stats.distance.toLocaleString('es-ES',{maximumFractionDigits:2})} km</span></div>}{recording&&<button className="stopRouteButton" disabled={busy} onClick={finish}>{busy?'Guardando…':'Finalizar y guardar ruta'}</button>}{!recording&&!armed&&<div className="gpsAutoHint">Abre primero una indicación de Google Maps para preparar el inicio automático.</div>}{message&&<small className="gpsMessage">{message}</small>}</>}</section>}

function RouteHistory({activities,close}){return <div className="routeDirectory routeHistory"><header><button onClick={close}>‹</button><div><small>EXPERIENCIAS</small><h1>Mis rutas</h1></div></header><div className="routeHistoryList">{activities.length?activities.map(activity=><article key={activity.id} className={activity.trophy_earned?'historyCompleted':'historyIncomplete'}><span>{activity.trophy_earned?'🏆':'!'}</span><div><strong>{activity.route_name||'Ruta guardada'}</strong><small>{activity.trophy_earned?'COMPLETADA':'INCOMPLETA'} · {Number(activity.distance_km||0).toLocaleString('es-ES',{maximumFractionDigits:1})} km</small></div></article>):<div className="routesState">Todavía no has grabado ninguna ruta.</div>}</div></div>}
