'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';

const FALLBACK_POSITION={lat:38.3452,lon:-0.4815};
const LEVEL_LABELS={principiante:'Principiante',intermedio:'Intermedio',experto:'Experto'};
const TERRITORIES={
 'Andalucía':['Almería','Cádiz','Córdoba','Granada','Huelva','Jaén','Málaga','Sevilla'],
 'Aragón':['Huesca','Teruel','Zaragoza'],'Principado de Asturias':['Asturias'],'Illes Balears':['Illes Balears'],
 'Canarias':['Las Palmas','Santa Cruz de Tenerife'],'Cantabria':['Cantabria'],
 'Castilla-La Mancha':['Albacete','Ciudad Real','Cuenca','Guadalajara','Toledo'],
 'Castilla y León':['Ávila','Burgos','León','Palencia','Salamanca','Segovia','Soria','Valladolid','Zamora'],
 'Cataluña':['Barcelona','Girona','Lleida','Tarragona'],'Comunidad Valenciana':['Alicante','Castellón','Valencia'],
 'Extremadura':['Badajoz','Cáceres'],'Galicia':['A Coruña','Lugo','Ourense','Pontevedra'],'La Rioja':['La Rioja'],
 'Comunidad de Madrid':['Madrid'],'Región de Murcia':['Murcia'],'Comunidad Foral de Navarra':['Navarra'],
 'País Vasco':['Álava','Bizkaia','Gipuzkoa'],'Ceuta':['Ceuta'],'Melilla':['Melilla']
};
const levelClass=level=>`routeLevel routeLevel-${level}`;
const value=(number,suffix)=>Number.isFinite(number)?`${number.toLocaleString('es-ES',{maximumFractionDigits:1})}${suffix}`:'No publicado';
function haversine(a,b){const rad=v=>v*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}

export default function RouteCatalog(){
 const[routes,setRoutes]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[catalogOpen,setCatalogOpen]=useState(false),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[placeQuery,setPlaceQuery]=useState(''),[catalogLabel,setCatalogLabel]=useState(''),[placeLoading,setPlaceLoading]=useState(false),[placeError,setPlaceError]=useState(''),[level,setLevel]=useState('todas'),[usingLocation,setUsingLocation]=useState(false),[completed,setCompleted]=useState({}),[historyOpen,setHistoryOpen]=useState(false);
 useEffect(()=>{let active=true;const load=position=>{const params=new URLSearchParams({lat:String(position.lat),lon:String(position.lon),radius:'20000'});fetch(`/api/routes?${params}`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'No se ha podido cargar el catálogo.');if(active){setRoutes(body.routes||[]);setLoading(false)}}).catch(err=>{if(active){setError(err.message);setLoading(false)}})};if(!navigator.geolocation)return load(FALLBACK_POSITION);navigator.geolocation.getCurrentPosition(({coords})=>{setUsingLocation(true);load({lat:coords.latitude,lon:coords.longitude})},()=>load(FALLBACK_POSITION),{enableHighAccuracy:false,timeout:7000,maximumAge:300000});return()=>{active=false}},[]);
 useEffect(()=>{const open=()=>setCatalogOpen(true),history=()=>setHistoryOpen(true);window.addEventListener('encumbrate:open-routes',open);window.addEventListener('encumbrate:open-route-history',history);return()=>{window.removeEventListener('encumbrate:open-routes',open);window.removeEventListener('encumbrate:open-route-history',history)}},[]);
 useEffect(()=>{loadCompleted()},[]);
 async function loadCompleted(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from('route_activities').select('id,external_route_key,route_name,route_difficulty,status,distance_km,duration_seconds,trophy_earned,ended_at').eq('user_id',user.id).order('started_at',{ascending:false});const map={};for(const activity of data||[])if(activity.external_route_key&&!map[activity.external_route_key])map[activity.external_route_key]=activity;setCompleted(map)}
 async function loadPlace(place,scope='place'){const clean=place.trim();if(!clean)return setPlaceError('Escribe una localidad o elige una provincia.');setPlaceLoading(true);setPlaceError('');try{const response=await fetch(`/api/routes?place=${encodeURIComponent(clean)}&radius=20000&scope=${scope}`);const body=await response.json();if(!response.ok)throw new Error(body.error||'No se ha podido buscar esa zona.');setRoutes(body.routes||[]);setCatalogLabel(body.searchLabel||clean);setUsingLocation(false);setQuery('');if(!(body.routes||[]).length)setPlaceError('No hay rutas públicas catalogadas cerca de esa zona.')}catch(error){setPlaceError(error.message||'No se ha podido buscar esa zona.')}finally{setPlaceLoading(false)}}
 async function searchPlace(event){event?.preventDefault();await loadPlace(placeQuery)}
 const filtered=useMemo(()=>routes.filter(route=>(level==='todas'||route.level===level)&&(!query.trim()||`${route.name} ${route.ref}`.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es')))),[routes,query,level]);
 const nearest=routes.slice(0,3);
 return <>
  <button className="cSearch routeSearchTrigger" onClick={()=>setCatalogOpen(true)} aria-label="Buscar entre todas las rutas"><span className="searchIcon">⌕</span><span>Buscar rutas por nombre…</span><b>☷</b></button>
  <div className="sectionTitle"><div><h2>{catalogLabel?`Rutas cerca de ${catalogLabel.split(',')[0]}`:'Rutas cerca de ti'}</h2><small>{catalogLabel?'Zona elegida en el buscador':usingLocation?'Ordenadas desde tu ubicación':'Mostrando Alicante como ubicación inicial'}</small></div><button onClick={()=>setCatalogOpen(true)}>Ver todas</button></div>
  {loading?<div className="routesState"><i/>Buscando rutas públicas cercanas…</div>:error?<div className="routesState routesError">{error}</div>:nearest.length?<div className="nearbyRoutes">{nearest.map(route=><RouteCard key={route.id} route={route} activity={completed[route.id]} onClick={()=>setSelected(route)}/>)}</div>:<div className="routesState">No hay rutas públicas catalogadas en este radio.</div>}
  {catalogOpen&&<RouteDirectory routes={filtered} completed={completed} query={query} setQuery={setQuery} placeQuery={placeQuery} setPlaceQuery={setPlaceQuery} searchPlace={searchPlace} loadPlace={loadPlace} placeLoading={placeLoading} placeError={placeError} catalogLabel={catalogLabel} level={level} setLevel={setLevel} close={()=>setCatalogOpen(false)} history={()=>{setCatalogOpen(false);setHistoryOpen(true)}} select={route=>{setCatalogOpen(false);setSelected(route)}}/>}
  {historyOpen&&<RouteHistory activities={Object.values(completed)} close={()=>setHistoryOpen(false)}/>}
  {selected&&<RouteDetail route={selected} activity={completed[selected.id]} close={()=>setSelected(null)} onSaved={loadCompleted}/>}
 </>
}

function RouteCard({route,onClick,activity}){return <button className={`nearbyRoute ${activity?.trophy_earned?'routeCompleted':''}`} onClick={onClick}><div className="routeCardPhoto"><img src={route.image} alt={`Vista asociada a ${route.name}`} onError={event=>{event.currentTarget.src='https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=800&q=80'}}/>{activity?.trophy_earned&&<span className="goldTrophy" aria-label="Ruta completada">🏆</span>}</div><div className="nearbyRouteBody"><div><span className={activity?.trophy_earned?'completedLabel':levelClass(route.level)}>{activity?.trophy_earned?'COMPLETADA':LEVEL_LABELS[route.level]}</span><small>{route.nearbyKm.toLocaleString('es-ES',{maximumFractionDigits:1})} km de ti</small></div><strong>{route.name}</strong>{route.ref&&<em>{route.ref}</em>}<p><b>{value(route.distanceKm,' km')}</b><span>↗ {value(route.ascentM,' m')}</span><span>△ {value(route.maxAltitudeM,' m')}</span></p></div><span className="routeChevron">›</span></button>}

function RouteDirectory({routes,completed,query,setQuery,placeQuery,setPlaceQuery,searchPlace,loadPlace,placeLoading,placeError,catalogLabel,level,setLevel,close,select,history}){const[community,setCommunity]=useState(''),[province,setProvince]=useState('');function chooseCommunity(event){setCommunity(event.target.value);setProvince('')}function chooseProvince(event){const value=event.target.value;setProvince(value);if(value){setPlaceQuery(value);loadPlace(`${value}, España`,'province')}}return <div className="routeDirectory"><header><button onClick={close}>‹</button><div><small>EXPERIENCIAS</small><h1>Buscador de rutas</h1></div><button className="historyButton" onClick={history} aria-label="Abrir mis rutas">🏆</button></header><div className="routeDirectoryControls"><div className="territorySelectors"><select value={community} onChange={chooseCommunity} aria-label="Elegir comunidad autónoma"><option value="">Comunidad autónoma</option>{Object.keys(TERRITORIES).map(name=><option key={name} value={name}>{name}</option>)}</select><select value={province} onChange={chooseProvince} disabled={!community||placeLoading} aria-label="Elegir provincia"><option value="">Provincia</option>{(TERRITORIES[community]||[]).map(name=><option key={name} value={name}>{name}</option>)}</select></div><form className="placeSearch" onSubmit={searchPlace}><label><span>⌖</span><input autoFocus value={placeQuery} onChange={event=>setPlaceQuery(event.target.value)} placeholder="O escribe: Bilbao, Picos de Europa…"/></label><button disabled={placeLoading}>{placeLoading?'Buscando…':'Buscar zona'}</button></form>{placeError&&<small className="placeSearchError">{placeError}</small>}<p className="searchArea">{catalogLabel?`Buscando alrededor de ${catalogLabel}`:'Elige comunidad y provincia, o busca cualquier localidad de España.'}</p><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filtrar por nombre de ruta"/></label><select value={level} onChange={event=>setLevel(event.target.value)} aria-label="Filtrar por nivel"><option value="todas">Todos los niveles</option><option value="principiante">Principiante</option><option value="intermedio">Intermedio</option><option value="experto">Experto</option></select></div><p className="routeCount">{routes.length} rutas encontradas en esta zona</p><div className="routeDirectoryList">{routes.map(route=><RouteCard key={route.id} route={route} activity={completed[route.id]} onClick={()=>select(route)}/>)}{!routes.length&&<div className="routesState">No hay coincidencias. Prueba otra provincia, localidad, nombre o nivel.</div>}</div><footer>Busca cualquier comunidad, provincia o localidad de España · Datos públicos · © OpenStreetMap contributors.</footer></div>}

function RouteDetail({route,activity,close,onSaved}){return <div className="routeScreen catalogRouteDetail"><div className="routePhoto" style={{backgroundImage:`linear-gradient(0deg,rgba(0,30,20,.92),transparent 62%),url(${route.image})`}}><button onClick={close} aria-label="Volver">‹</button>{activity?.trophy_earned&&<div className="detailTrophy">🏆 <b>COMPLETADA</b></div>}<div className="routeName"><span>{route.nearbyKm.toLocaleString('es-ES',{maximumFractionDigits:1})} km desde tu ubicación</span><h1>{route.name}</h1><b className={levelClass(route.level)}>{LEVEL_LABELS[route.level]}</b></div></div><section className="routeSheet"><div className="routeStats"><div><strong>{value(route.distanceKm,' km')}</strong><small>Distancia</small></div><div><strong>{value(route.ascentM,' m')}</strong><small>Desnivel +</small></div><div><strong>{value(route.maxAltitudeM,' m')}</strong><small>Altitud máx.</small></div><div><strong>{route.duration||'No publicado'}</strong><small>Duración</small></div></div><p>{route.description}</p><div className="routeFacts"><div><small>Nivel orientativo</small><strong>{LEVEL_LABELS[route.level]}</strong></div><div><small>Recorrido</small><strong>{route.routeType}</strong></div><div><small>Altitud mínima</small><strong>{value(route.minAltitudeM,' m')}</strong></div><div><small>Red senderista</small><strong>{route.network||'No publicada'}</strong></div></div><GpsRecorder route={route} previous={activity} onSaved={onSaved}/>{!route.imageIsSpecific&&<p className="routePhotoNotice">La fuente no incluye una fotografía verificable del trazado; se muestra una imagen ambiental provisional.</p>}<a className="mapBtn routeSource" href={route.officialUrl||route.sourceUrl} target="_blank" rel="noopener noreferrer">Consultar fuente pública ↗</a><p className="routeSafety">Comprueba señalización, meteorología y avisos oficiales antes de salir. La copa acredita el registro GPS dentro de Encúmbrate; no sustituye una homologación oficial.</p></section></div>}

function GpsRecorder({route,previous,onSaved}){const[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[stats,setStats]=useState({points:0,distance:0});const watchRef=useRef(null),activityRef=useRef(null),pointsRef=useRef([]),sequenceRef=useRef(0);
 useEffect(()=>()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current)},[]);
 async function start(){setBusy(true);setMessage('Preparando el GPS…');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Inicia sesión para guardar la ruta.');if(!navigator.geolocation)throw new Error('Este dispositivo no ofrece ubicación GPS.');const{data:activity,error}=await supabase.from('route_activities').insert({user_id:user.id,external_route_key:route.id,route_name:route.name,route_difficulty:route.level,planned_distance_km:route.distanceKm||null,status:'recording'}).select('id,started_at').single();if(error)throw error;activityRef.current={...activity,userId:user.id};pointsRef.current=[];sequenceRef.current=0;watchRef.current=navigator.geolocation.watchPosition(position=>savePoint(position,user.id,activity.id),gpsError=>setMessage(gpsError.code===1?'Activa el permiso de ubicación para grabar la ruta.':'Se ha perdido temporalmente la señal GPS.'),{enableHighAccuracy:true,maximumAge:3000,timeout:15000});setRecording(true);setMessage('Grabando recorrido GPS. Mantén Encúmbrate abierta.')}catch(error){setMessage(error.message||'No hemos podido iniciar la grabación.')}finally{setBusy(false)}}
 async function savePoint(position,userId,activityId){const point={lat:position.coords.latitude,lon:position.coords.longitude,altitude:position.coords.altitude,accuracy:position.coords.accuracy,at:new Date(position.timestamp).toISOString()};if(point.accuracy>100)return;const previous=pointsRef.current.at(-1);if(previous&&haversine(previous,point)<.005)return;pointsRef.current.push(point);sequenceRef.current+=1;let distance=0;for(let i=1;i<pointsRef.current.length;i++)distance+=haversine(pointsRef.current[i-1],pointsRef.current[i]);setStats({points:pointsRef.current.length,distance});const{error}=await supabase.from('activity_gps_points').insert({activity_id:activityId,user_id:userId,sequence_number:sequenceRef.current,recorded_at:point.at,latitude:point.lat,longitude:point.lon,accuracy_m:point.accuracy,altitude_m:point.altitude});if(error)setMessage('Seguimos grabando, pero un punto GPS no ha podido guardarse.')}
 async function finish(){setBusy(true);if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;const{data,error}=await supabase.rpc('finalize_external_route_activity',{p_activity_id:activityRef.current.id});setRecording(false);setBusy(false);if(error)return setMessage('La grabación terminó, pero no hemos podido guardar el resultado.');setMessage(data?.trophy_earned?'¡Ruta completada! Has conseguido la copa dorada.':'Ruta guardada como incompleta. Podrás volver a intentarla.');onSaved?.()}
 return <section className="gpsRecorder">{previous?.trophy_earned?<div className="gpsCompleted"><span>🏆</span><div><strong>Ruta completada</strong><small>{Number(previous.distance_km||0).toLocaleString('es-ES',{maximumFractionDigits:1})} km registrados</small></div></div>:<><h2>Grabar esta ruta con GPS</h2><p>Encúmbrate guardará tus pasos mientras caminas. La copa se concede al registrar al menos el 80 % de la distancia publicada y un mínimo de 20 puntos GPS.</p>{recording&&<div className="gpsLive"><b>● EN GRABACIÓN</b><span>{stats.points} puntos</span><span>{stats.distance.toLocaleString('es-ES',{maximumFractionDigits:2})} km</span></div>}<button className={recording?'stopRouteButton':'startRouteButton'} disabled={busy} onClick={recording?finish:start}>{busy?'Espera…':recording?'Finalizar y guardar ruta':'Iniciar ruta con GPS'}</button>{message&&<small className="gpsMessage">{message}</small>}</>}</section>}

function RouteHistory({activities,close}){return <div className="routeDirectory routeHistory"><header><button onClick={close}>‹</button><div><small>EXPERIENCIAS</small><h1>Mis rutas</h1></div></header><div className="routeHistoryList">{activities.length?activities.map(activity=><article key={activity.id} className={activity.trophy_earned?'historyCompleted':'historyIncomplete'}><span>{activity.trophy_earned?'🏆':'!'}</span><div><strong>{activity.route_name||'Ruta guardada'}</strong><small>{activity.trophy_earned?'COMPLETADA':'INCOMPLETA'} · {Number(activity.distance_km||0).toLocaleString('es-ES',{maximumFractionDigits:1})} km</small></div></article>):<div className="routesState">Todavía no has grabado ninguna ruta.</div>}</div></div>}
