'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import './social-chat.css';

export default function SocialChat({user}){
 const[expanded,setExpanded]=useState(false),[alias,setAlias]=useState(''),[aliases,setAliases]=useState([]),[messages,setMessages]=useState([]),[conversations,setConversations]=useState([]),[room,setRoom]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),bottom=useRef(null);
 const aliasMap=useMemo(()=>Object.fromEntries(aliases.map(item=>[item.user_id,item.alias])),[aliases]),myAlias=aliasMap[user.id]||alias;
 useEffect(()=>{if(expanded)load()},[expanded,user.id]);
 useEffect(()=>{if(!expanded)return;const channel=supabase.channel('encumbrate-social-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'social_messages'},payload=>{const message=payload.new;if((room===null&&message.conversation_id===null)||(room&&message.conversation_id===room))setMessages(current=>current.some(item=>item.id===message.id)?current:[...current,message])}).subscribe();return()=>supabase.removeChannel(channel)},[expanded,room]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages]);
 async function load(){setBusy(true);const[{data:people},{data:mine},{data:chats}]=await Promise.all([supabase.from('social_aliases').select('user_id,alias').order('alias'),supabase.from('social_aliases').select('alias').eq('user_id',user.id).maybeSingle(),supabase.from('private_conversations').select('*').order('created_at',{ascending:false})]);setAliases(people||[]);setAlias(mine?.alias||'');setConversations(chats||[]);await loadMessages(room);setBusy(false)}
 async function loadMessages(conversation){let query=supabase.from('social_messages').select('id,sender_id,conversation_id,body,created_at').order('created_at',{ascending:true}).limit(100);query=conversation?query.eq('conversation_id',conversation):query.is('conversation_id',null);const{data}=await query;setMessages(data||[])}
 async function saveAlias(event){event.preventDefault();const value=alias.trim();if(value.length<3)return setError('El alias necesita al menos 3 caracteres.');setBusy(true);const{error}=await supabase.from('social_aliases').upsert({user_id:user.id,alias:value,updated_at:new Date().toISOString()});setBusy(false);if(error)return setError(error.code==='23505'?'Ese alias ya está siendo utilizado.':'No hemos podido guardar el alias.');setError('');await load()}
 async function send(event){event.preventDefault();const form=event.currentTarget,input=form.elements.message,body=input.value.trim();if(!body||!myAlias)return;input.value='';const{error}=await supabase.from('social_messages').insert({sender_id:user.id,conversation_id:room,body});if(error){input.value=body;setError('No hemos podido enviar el mensaje.')} }
 async function openPrivate(other){setBusy(true);const{data,error}=await supabase.rpc('start_private_conversation',{p_other_user:other});if(error){setError('No hemos podido abrir el chat privado.');setBusy(false);return}setRoom(data);await loadMessages(data);setBusy(false)}
 async function chooseRoom(id){setRoom(id);setBusy(true);await loadMessages(id);setBusy(false)}
 const otherFor=id=>{const chat=conversations.find(item=>item.id===id);return chat?(chat.user_a===user.id?chat.user_b:chat.user_a):null},roomName=room?aliasMap[otherFor(room)]||'Chat privado':'Chat general';
 if(!expanded)return <button className="openSocialChat" onClick={()=>setExpanded(true)}><span>●</span><div><b>Chat en directo</b><small>Habla con toda la comunidad o en privado</small></div><strong>›</strong></button>;
 return <section className="socialChat"><header><button onClick={()=>setExpanded(false)}>‹</button><div><small>EN DIRECTO</small><h2>{roomName}</h2></div><span>●</span></header>{!myAlias?<form className="aliasSetup" onSubmit={saveAlias}><h3>Elige cómo te verán</h3><p>Utiliza un nombre o alias público. Tu correo seguirá siendo privado.</p><input value={alias} onChange={event=>setAlias(event.target.value)} minLength="3" maxLength="30" placeholder="Tu alias"/><button disabled={busy}>Guardar alias</button>{error&&<small>{error}</small>}</form>:<><nav className="chatRooms"><button className={!room?'active':''} onClick={()=>chooseRoom(null)}>Todos</button>{conversations.map(chat=>{const other=chat.user_a===user.id?chat.user_b:chat.user_a;return <button className={room===chat.id?'active':''} key={chat.id} onClick={()=>chooseRoom(chat.id)}>@{aliasMap[other]||'viajero'}</button>})}</nav><div className="chatPeople"><b>Mensaje privado:</b>{aliases.filter(item=>item.user_id!==user.id).slice(0,20).map(person=><button key={person.user_id} onClick={()=>openPrivate(person.user_id)}>@{person.alias}</button>)}</div><div className="chatMessages">{busy?<p>Actualizando conversación…</p>:messages.length?messages.map(message=><article className={message.sender_id===user.id?'mine':''} key={message.id}><div><b>{message.sender_id===user.id?'Tú':aliasMap[message.sender_id]||'Viajero'}</b><small>{new Date(message.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}</small></div><p>{message.body}</p></article>):<p className="chatEmpty">Todavía no hay mensajes. Empieza la conversación.</p>}<span ref={bottom}/></div><form className="chatComposer" onSubmit={send}><input name="message" maxLength="1000" autoComplete="off" placeholder={room?'Mensaje privado…':'Mensaje para toda la comunidad…'}/><button aria-label="Enviar mensaje">➤</button></form>{error&&<p className="chatError">{error}</p>}</>}</section>
}

