'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import ReportUserModal from './ReportUserModal';
import './social-chat.css';

export default function SocialChat({user}){
 const[expanded,setExpanded]=useState(false),[alias,setAlias]=useState(''),[aliases,setAliases]=useState([]),[messages,setMessages]=useState([]),[conversations,setConversations]=useState([]),[room,setRoom]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reportUser,setReportUser]=useState(null),bottom=useRef(null);
 const aliasMap=useMemo(()=>Object.fromEntries(aliases.map(item=>[item.user_id,item.alias])),[aliases]),myAlias=aliasMap[user.id]||'';
 useEffect(()=>{if(expanded)load()},[expanded,user.id]);
 useEffect(()=>{if(!expanded)return;const channel=supabase.channel('encumbrate-social-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'social_messages'},payload=>{const message=payload?.new;if(!message?.id)return;if((room===null&&message.conversation_id===null)||(room&&message.conversation_id===room))setMessages(current=>current.some(item=>item.id===message.id)?current:[...current,message])}).subscribe();return()=>{supabase.removeChannel(channel)}},[expanded,room]);
 useEffect(()=>{try{bottom.current?.scrollIntoView?.({behavior:'smooth'})}catch{}},[messages]);
 async function load(){setBusy(true);const[{data:people},{data:mine},{data:chats}]=await Promise.all([supabase.from('social_aliases').select('user_id,alias').order('alias'),supabase.from('social_aliases').select('alias').eq('user_id',user.id).maybeSingle(),supabase.from('private_conversations').select('*').order('created_at',{ascending:false})]);setAliases(people||[]);setAlias(mine?.alias||'');setConversations(chats||[]);await loadMessages(room);setBusy(false)}
 async function loadMessages(conversation){let query=supabase.from('social_messages').select('id,sender_id,conversation_id,body,created_at').order('created_at',{ascending:true}).limit(100);query=conversation?query.eq('conversation_id',conversation):query.is('conversation_id',null);const{data}=await query;setMessages(data||[])}
 async function saveAlias(event){event.preventDefault();const value=alias.trim();if(value.length<3)return setError('El alias necesita al menos 3 caracteres.');setBusy(true);const{error}=await supabase.rpc('set_social_alias',{p_alias:value});setBusy(false);if(error){const detail=error.message||'';return setError(detail.includes('alias_taken')?'Ese alias ya está siendo utilizado.':detail.includes('prohibited_alias')?'Ese alias no está permitido. Elige uno respetuoso.':detail.includes('invalid_alias')?'Usa entre 3 y 30 letras, números, espacios, guiones o guion bajo.':'No hemos podido guardar el alias.')}setError('');await load()}
 async function send(event){event.preventDefault();const form=event.currentTarget,input=form.elements.message,body=input.value.trim();if(!body||!myAlias)return;input.value='';setError('');try{const{data,error}=await supabase.rpc('send_social_message',{p_body:body,p_conversation_id:room});if(error)throw error;if(data?.status==='suspended'){setError('Cuenta suspendida por incumplir las normas de convivencia.');window.dispatchEvent(new CustomEvent('encumbrate:account-suspended'));return}}catch{input.value=body;setError('No hemos podido enviar el mensaje. Inténtalo de nuevo.')} }
 async function openPrivate(other){setBusy(true);const{data,error}=await supabase.rpc('start_private_conversation',{p_other_user:other});if(error){setError('No hemos podido abrir el chat privado.');setBusy(false);return}setRoom(data);await loadMessages(data);setBusy(false)}
 async function chooseRoom(id){setRoom(id);setBusy(true);await loadMessages(id);setBusy(false)}
 const otherFor=id=>{const chat=conversations.find(item=>item.id===id);return chat?(chat.user_a===user.id?chat.user_b:chat.user_a):null},roomName=room?aliasMap[otherFor(room)]||'Chat privado':'Chat general';
 if(!expanded)return <button className="openSocialChat" onClick={()=>setExpanded(true)}><span>●</span><div><b>Chat en directo</b><small>Habla con toda la comunidad o en privado</small></div><strong>›</strong></button>;
 return <section className="socialChat"><header><button onClick={()=>setExpanded(false)}>‹</button><div><small>EN DIRECTO</small><h2>{roomName}</h2></div><span>●</span></header>{!myAlias?<form className="aliasSetup" onSubmit={saveAlias}><h3>Elige cómo te verán</h3><p>Utiliza un alias público, único y respetuoso. Tu correo seguirá siendo privado.</p><input value={alias} onChange={event=>setAlias(event.target.value)} minLength="3" maxLength="30" placeholder="Tu alias"/><button disabled={busy}>Guardar alias</button>{error&&<small>{error}</small>}</form>:<><nav className="chatRooms"><button className={!room?'active':''} onClick={()=>chooseRoom(null)}>Todos</button>{conversations.map(chat=>{const other=chat.user_a===user.id?chat.user_b:chat.user_a;return <button className={room===chat.id?'active':''} key={chat.id} onClick={()=>chooseRoom(chat.id)}>@{aliasMap[other]||'viajero'}</button>})}</nav><div className="chatPeople"><b>Mensaje privado:</b>{aliases.filter(item=>item.user_id!==user.id).slice(0,20).map(person=><button key={person.user_id} onClick={()=>openPrivate(person.user_id)}>@{person.alias}</button>)}</div><div className="chatMessages">{busy?<p>Actualizando conversación…</p>:messages.length?messages.map(message=><article className={message.sender_id===user.id?'mine':''} key={message.id}><div><b>{message.sender_id===user.id?'Tú':aliasMap[message.sender_id]||'Viajero'}{message.sender_id!==user.id&&<button className="chatReport" onClick={()=>setReportUser({user_id:message.sender_id,alias:aliasMap[message.sender_id]||'Viajero'})}>Denunciar</button>}</b><small>{message.created_at?new Date(message.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):''}</small></div><p>{String(message.body||'')}</p></article>):<p className="chatEmpty">Todavía no hay mensajes. Empieza la conversación.</p>}<span ref={bottom}/></div><form className="chatComposer" onSubmit={send}><input name="message" maxLength="1000" autoComplete="off" placeholder={room?'Mensaje privado…':'Mensaje para toda la comunidad…'}/><button aria-label="Enviar mensaje">➤</button></form>{error&&<p className="chatError">{error}</p>}</>}{reportUser&&<ReportUserModal user={user} reported={reportUser} close={()=>setReportUser(null)}/>}</section>
}
