'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import ReportUserModal from './ReportUserModal';
import './social-chat.css';
import './social-chat-stability.css';
import './social-achievements.css';
import './chat-actions.css';

export default function SocialChat({user}){
 const[expanded,setExpanded]=useState(false),[profileAlias,setProfileAlias]=useState(null),[aliases,setAliases]=useState([]),[messages,setMessages]=useState([]),[achievements,setAchievements]=useState([]),[publicView,setPublicView]=useState('chat'),[conversations,setConversations]=useState([]),[room,setRoom]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reportUser,setReportUser]=useState(null),[actionUser,setActionUser]=useState(null),bottom=useRef(null),loadSequence=useRef(0);
 const aliasMap=useMemo(()=>Object.fromEntries(aliases.map(item=>[item.user_id,item.alias])),[aliases]),myAlias=profileAlias||'';
 useEffect(()=>{setProfileAlias(null);setAliases([])},[user.id]);
 useEffect(()=>{if(expanded)load()},[expanded,user.id]);
 useEffect(()=>{if(!expanded)return;const channel=supabase.channel('encumbrate-social-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'social_messages'},payload=>{const message=payload?.new;if(!message?.id)return;if((room===null&&message.conversation_id===null)||(room&&message.conversation_id===room))setMessages(current=>current.some(item=>item.id===message.id)?current:[...current,message])}).on('postgres_changes',{event:'INSERT',schema:'public',table:'social_achievement_posts'},payload=>{const achievement=payload?.new;if(achievement?.id)setAchievements(current=>current.some(item=>item.id===achievement.id)?current:[achievement,...current])}).subscribe();return()=>{supabase.removeChannel(channel)}},[expanded,room]);
 useEffect(()=>{try{bottom.current?.scrollIntoView?.({behavior:'smooth'})}catch{}},[messages]);
 async function load(){const sequence=++loadSequence.current;setBusy(true);setError('');try{const results=await Promise.all([supabase.from('social_aliases').select('user_id,alias').order('alias'),supabase.from('social_aliases').select('alias').eq('user_id',user.id).maybeSingle(),supabase.from('private_conversations').select('*').order('created_at',{ascending:false}),supabase.from('social_achievement_posts').select('id,user_id,achievement_key,title,description,badge_icon,metadata,achieved_at,created_at').order('created_at',{ascending:false}).limit(50)]);if(sequence!==loadSequence.current)return;const failed=results.find(result=>result.error);if(failed?.error)throw failed.error;const[people,mine,chats,awards]=results.map(result=>result.data);let confirmed=mine?.alias||'';if(!confirmed){const automatic=`Senderista-${String(user.id).replace(/[^a-z0-9]/gi,'').slice(0,12).toUpperCase()}`,{error:aliasError}=await supabase.rpc('set_social_alias',{p_alias:automatic});if(aliasError)throw aliasError;confirmed=automatic}if(sequence!==loadSequence.current)return;setProfileAlias(confirmed);setAliases(()=>{const list=people||[];return list.some(item=>item.user_id===user.id)?list:[...list,{user_id:user.id,alias:confirmed}]});setConversations(chats||[]);setAchievements(awards||[]);await loadMessages(room)}catch{if(sequence===loadSequence.current)setError('No hemos podido preparar tu acceso al chat. Comprueba la conexión e inténtalo de nuevo.')}finally{if(sequence===loadSequence.current)setBusy(false)}}
 async function loadMessages(conversation){let query=supabase.from('social_messages').select('id,sender_id,conversation_id,body,created_at').order('created_at',{ascending:true}).limit(100);query=conversation?query.eq('conversation_id',conversation):query.is('conversation_id',null);const{data,error}=await query;if(error)throw error;setMessages(data||[])}
 async function send(event){event.preventDefault();const form=event.currentTarget,input=form.elements.message,body=input.value.trim();if(!body||!myAlias)return;input.value='';setError('');try{const{data,error}=await supabase.rpc('send_social_message',{p_body:body,p_conversation_id:room});if(error)throw error;if(data?.status==='personal_data_blocked'){input.value=body;setError('No publiques teléfonos, correos, DNI/NIE, IBAN ni datos bancarios. Elimínalos antes de enviar.');return}if(data?.status==='warning'){input.value=body;setError(`Mensaje bloqueado por lenguaje potencialmente ofensivo. Aviso ${3-Number(data.remaining||0)} de 3; puedes corregirlo o solicitar revisión.`);return}if(data?.status==='restricted'){setError('Chat limitado temporalmente mientras el equipo revisa los avisos. El resto de Encúmbrate continúa disponible.');return}}catch{input.value=body;setError('No hemos podido enviar el mensaje. Inténtalo de nuevo.')}}
 async function openPrivate(other){setActionUser(null);setBusy(true);const{data,error}=await supabase.rpc('start_private_conversation',{p_other_user:other});if(error){setError('No hemos podido abrir el chat privado.');setBusy(false);return}setRoom(data);setPublicView('chat');const{data:chats}=await supabase.from('private_conversations').select('*').order('created_at',{ascending:false});setConversations(chats||[]);await loadMessages(data);setBusy(false)}
 async function chooseRoom(id){setRoom(id);setPublicView('chat');setBusy(true);await loadMessages(id);setBusy(false)}
 const otherFor=id=>{const chat=conversations.find(item=>item.id===id);return chat?(chat.user_a===user.id?chat.user_b:chat.user_a):null},roomName=room?aliasMap[otherFor(room)]||'Chat privado':'Chat general';
 const identify=message=>({user_id:message.sender_id,alias:aliasMap[message.sender_id]||'Viajero'});
 if(!expanded)return <button className="openSocialChat" onClick={()=>setExpanded(true)}><span>●</span><div><b>Chat en directo</b><small>Habla con toda la comunidad o en privado</small></div><strong>›</strong></button>;
 return <section className="socialChat">
  <header><button onClick={()=>setExpanded(false)}>‹</button><div><small>EN DIRECTO</small><h2>{publicView==='achievements'&&!room?'Logros de la comunidad':roomName}</h2></div><span>●</span></header>
  {profileAlias===null?<div className="aliasSetup aliasLoading"><i/><h3>Preparando el chat…</h3><p>Estamos comprobando tu perfil público y creando un alias seguro si lo necesitas.</p>{error&&<><small>{error}</small><button type="button" onClick={load}>Reintentar</button></>}</div>:<>
   <nav className="chatRooms"><button className={!room&&publicView==='chat'?'active':''} onClick={()=>chooseRoom(null)}>Todos</button>{!room&&<button className={publicView==='achievements'?'active achievementTab':''} onClick={()=>setPublicView('achievements')}>🏆 Logros</button>}{conversations.map(chat=>{const other=chat.user_a===user.id?chat.user_b:chat.user_a;return <button className={room===chat.id?'active':''} key={chat.id} onClick={()=>chooseRoom(chat.id)}>@{aliasMap[other]||'viajero'}</button>})}</nav>
   {publicView==='achievements'&&!room?<><div className="achievementIntro"><span>✦</span><div><b>Logros de la comunidad</b><small>Publicaciones oficiales verificadas por Encúmbrate</small></div></div><div className="achievementFeed">{busy?<p>Actualizando logros…</p>:achievements.length?achievements.map(item=><article className="achievementCard" key={item.id}><div className="achievementGlow"/><span className="achievementIcon">{item.badge_icon||'🏅'}</span><div className="achievementCopy"><small>LOGRO OFICIAL · ENCÚMBRATE</small><h3>{item.title}</h3><b>@{aliasMap[item.user_id]||'Viajero'}</b><p>{item.description}</p><time>{new Date(item.achieved_at||item.created_at).toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}</time></div><i aria-label="Verificado">✓</i></article>):<p className="chatEmpty">Los próximos logros verificados aparecerán aquí automáticamente.</p>}</div></>:<>
   <div className="chatPeople"><b>Mensaje privado:</b>{aliases.filter(item=>item.user_id!==user.id).slice(0,20).map(person=><button key={person.user_id} onClick={()=>openPrivate(person.user_id)}>@{person.alias}</button>)}</div>
   <div className="chatPrivacy">Protege tu privacidad: no publiques teléfonos, correos, DNI/NIE ni datos bancarios.</div>
   <div className="chatMessages">{busy?<p>Actualizando conversación…</p>:messages.length?messages.map(message=>{const mine=message.sender_id===user.id;return <article className={mine?'mine':'clickable'} key={message.id} onClick={()=>!mine&&setActionUser(identify(message))}><div><b>{mine?'Tú':aliasMap[message.sender_id]||'Viajero'}</b><small>{message.created_at?new Date(message.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):''}</small></div><p>{String(message.body||'')}</p>{!mine&&<button className="chatReport" onClick={event=>{event.stopPropagation();setReportUser(identify(message))}}>Denunciar usuario</button>}</article>}):<p className="chatEmpty">Todavía no hay mensajes. Empieza la conversación.</p>}<span ref={bottom}/></div>
   <form className="chatComposer" onSubmit={send}><input name="message" maxLength="1000" autoComplete="off" placeholder={room?'Mensaje privado…':'Mensaje para toda la comunidad…'}/><button aria-label="Enviar mensaje">➤</button></form>{error&&<p className="chatError">{error}</p>}</>}
  </>}
  {actionUser&&<div className="chatUserActions" onClick={()=>setActionUser(null)}><section onClick={event=>event.stopPropagation()}><small>USUARIO</small><h3>@{actionUser.alias}</h3><button onClick={()=>openPrivate(actionUser.user_id)}>Enviar mensaje privado</button><button className="danger" onClick={()=>{setReportUser(actionUser);setActionUser(null)}}>Denunciar usuario</button><button className="cancel" onClick={()=>setActionUser(null)}>Cancelar</button></section></div>}
  {reportUser&&<ReportUserModal user={user} reported={reportUser} close={()=>setReportUser(null)}/>}
 </section>
}
