export const HELP_TOPICS = [
  { id:'routes', group:'Primeros pasos', title:'¿Cómo encuentro una ruta?', text:'Abre Explorar desde el menú. Busca por nombre o zona y consulta la distancia, el desnivel y la duración. El nivel es orientativo: revisa también la información práctica y tus propias condiciones.', action:'explore', label:'Abrir Explorar' },
  { id:'prepare', group:'Primeros pasos', title:'¿Cómo preparo mi salida y una quedada?', text:'Abre la ficha de una ruta. En Preparar mi salida puedes revisar el material y guardar el trazado. En esa misma ficha encontrarás Crear quedada para esta ruta y los accesos al sendero.' },
  { id:'gps', group:'Durante la ruta', title:'¿Cómo inicio y finalizo el recorrido GPS?', text:'En la ficha de la ruta utiliza el control de iniciar y concede el permiso de ubicación cuando se solicite. Comprueba que el registro está activo. Al terminar usa el control de finalizar y espera la confirmación. No borres los datos del navegador si hay una sesión pendiente.' },
  { id:'compass', group:'Durante la ruta', title:'La brújula no gira o marca una dirección inestable', text:'Comprueba que tu dispositivo dispone de sensor de orientación y que el navegador permite acceder a él. Aléjalo de imanes y objetos metálicos. Sigue las indicaciones de calibración que aparezcan. No interpretes una lectura inmóvil como una dirección fiable.', action:'compass', label:'Abrir curso de brújula' },
  { id:'lost', group:'Durante la ruta', title:'¿Qué hace Estoy perdido?', text:'Durante la navegación, esta función ayuda a consultar tu posición y el trazado. Un retorno calculado es orientativo, no garantiza que el terreno sea transitable. Sin Internet no se puede calcular un camino nuevo con el servidor. Si hay una emergencia, utiliza el 112.' },
  { id:'offline', group:'Sin conexión', title:'¿Qué se descarga para usar sin Internet?', text:'En la web, guardar trazado conserva los puntos de la ruta en este dispositivo. No descarga el mapa de fondo completo. Prepara la salida con conexión y comprueba las descargas. Las descargas nativas de Android son independientes; la prueba física completa en modo avión sigue pendiente.', action:'settings', label:'Consultar descargas en Configuración' },
  { id:'download', group:'Solucionar problemas', title:'No puedo descargar una ruta', text:'Comprueba tu conexión y el espacio disponible. Vuelve a intentarlo y espera la confirmación de guardado. En Configuración puedes consultar los trazados descargados y eliminar los que ya no necesites. No elimines el que estés usando en una salida.', action:'settings', label:'Abrir Configuración' },
  { id:'location', group:'Solucionar problemas', title:'El GPS no encuentra mi ubicación', text:'Comprueba que la ubicación del móvil esté activada y que hayas concedido el permiso al navegador o aplicación. Busca un lugar con mejor visión del cielo y espera una nueva lectura. Configuración muestra el estado de los permisos cuando el navegador lo permite.', action:'settings', label:'Consultar permisos' },
  { id:'photos', group:'Solucionar problemas', title:'La foto no se guarda', text:'Comprueba el permiso de cámara y la conexión. Espera a que termine el aviso de guardado antes de cerrar o actualizar. Si aparece un error, conserva la foto e inténtalo de nuevo; para el avatar también puedes elegirla desde la galería.' },
  { id:'update', group:'Solucionar problemas', title:'No aparecen los últimos cambios', text:'Con conexión, cierra y vuelve a abrir Encúmbrate o actualiza la página cuando no estés registrando una ruta. No borres el almacenamiento como primer paso: podrías perder trazados y datos pendientes de sincronizar.' },
];
export function searchHelp(query) {
  const normalize = value => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es');
  const words=normalize(query.trim()).split(/\s+/).filter(Boolean);
  return HELP_TOPICS.filter(topic=>words.every(word=>normalize(`${topic.group} ${topic.title} ${topic.text}`).includes(word)));
}
