import {OFFLINE_MAP_PROFILES,OFFLINE_MAP_SOURCE,SPAIN_OFFLINE_BOUNDS,offlineRegionId} from './offline-regions.js';
const DB='encumbrate-offline-mosaic',VER=1,TILES='tiles',PACKS='packs',MAX_TILES=12000,EST=60*1024,MAX_BLOB=1024*1024,WORKERS=4;
const finite=v=>Number.isFinite(Number(v)),clampLat=v=>Math.max(-85.05112878,Math.min(85.05112878,Number(v)));
export function normalizeOfflineBounds(b){if(!Array.isArray(b)||b.length!==4||!b.every(finite))throw Error('Límites de mapa no válidos.');const [w,s,e,n]=b.map(Number);if(w<-180||e>180||s<-85.052||n>85.052||e<=w||n<=s)throw Error('Límites de mapa no válidos.');return[w,s,e,n]}
const xTile=(lon,z)=>Math.max(0,Math.min(2**z-1,Math.floor((Number(lon)+180)/360*2**z)));
const yTile=(lat,z)=>{const r=clampLat(lat)*Math.PI/180;return Math.max(0,Math.min(2**z-1,Math.floor((1-Math.asinh(Math.tan(r))/Math.PI)/2*2**z)))};
export const offlineTileKey=(z,x,y)=>`${z}/${x}/${y}`;
export function offlineTilesForBounds(bounds,minZoom,maxZoom,{limit=MAX_TILES}={}){const[w,s,e,n]=normalizeOfflineBounds(bounds),out=[];for(let z=Math.floor(minZoom);z<=Math.floor(maxZoom);z++){for(let x=xTile(w,z);x<=xTile(e,z);x++)for(let y=yTile(n,z);y<=yTile(s,z);y++){out.push({z,x,y,key:offlineTileKey(z,x,y)});if(out.length>limit)throw Error('La zona es demasiado grande para este nivel de detalle. Elige una provincia o una ruta concreta.')}}return out}
export const estimateOfflinePackBytes=(b,min,max)=>offlineTilesForBounds(b,min,max).length*EST;
export const offlineTileUrl=t=>`/api/maps/offline?z=${t.z}&x=${t.x}&y=${t.y}&size=256`;
function open(){if(typeof indexedDB==='undefined')return Promise.reject(Error('El almacenamiento offline no está disponible.'));return new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(TILES))d.createObjectStore(TILES,{keyPath:'key'});if(!d.objectStoreNames.contains(PACKS))d.createObjectStore(PACKS,{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);r.onblocked=()=>no(Error('El almacén de mapas está ocupado.'))})}
const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const get=(d,s,k)=>req(d.transaction(s,'readonly').objectStore(s).get(k));
const all=(d,s)=>req(d.transaction(s,'readonly').objectStore(s).getAll());
const put=(d,s,v)=>new Promise((ok,no)=>{const t=d.transaction(s,'readwrite');t.objectStore(s).put(v);t.oncomplete=()=>ok(v);t.onerror=t.onabort=()=>no(t.error)});
const del=(d,s,k)=>new Promise((ok,no)=>{const t=d.transaction(s,'readwrite');t.objectStore(s).delete(k);t.oncomplete=ok;t.onerror=t.onabort=()=>no(t.error)});
export async function getOfflinePack(id){const d=await open();try{return await get(d,PACKS,String(id))}finally{d.close()}}
export async function listOfflinePacks(){const d=await open();try{return(await all(d,PACKS)).sort((a,b)=>String(b.savedAt||'').localeCompare(String(a.savedAt||'')))}finally{d.close()}}
export async function offlineMosaicStats(){const d=await open();try{const ts=await all(d,TILES),ps=await all(d,PACKS);return{bytes:ts.reduce((n,t)=>n+Number(t.bytes||t.blob?.size||0),0),tileCount:ts.length,packCount:ps.length}}finally{d.close()}}
async function capacity(bytes){try{const e=await navigator.storage?.estimate?.();if(e?.quota&&bytes>(e.quota-(e.usage||0))*.9)throw Error('No hay espacio suficiente para esta descarga. Elimina mapas antiguos o descarga una zona menor.')}catch(e){if(/No hay espacio/.test(e?.message||''))throw e}}
async function valid(blob){if(!(blob instanceof Blob)||!blob.size||blob.size>MAX_BLOB||!blob.type.startsWith('image/'))throw Error('La cartografía recibida no es válida.');if(typeof createImageBitmap==='function'){const i=await createImageBitmap(blob);try{if(!i.width||!i.height)throw Error('La cartografía no se puede representar.')}finally{i.close()}}}
export async function downloadOfflinePack(spec,{signal,fetcher=fetch,onProgress}={}){if(!spec?.id||!spec?.name)throw Error('Zona offline no válida.');const tiles=offlineTilesForBounds(spec.bounds,spec.minZoom,spec.maxZoom);await capacity(tiles.length*EST);try{await navigator.storage?.persist?.()}catch{}const d=await open(),base={...spec,totalTiles:tiles.length,completedTiles:0,totalBytes:0,status:'downloading',savedAt:new Date().toISOString(),source:OFFLINE_MAP_SOURCE,tileKeys:tiles.map(t=>t.key)};await put(d,PACKS,base);let next=0,done=0,bytes=0,failed=null;const worker=async()=>{while(!failed){if(signal?.aborted){failed=Error('Descarga cancelada.');break}const t=tiles[next++];if(!t)break;try{let old=await get(d,TILES,t.key);if(old?.blob?.size){const packIds=[...new Set([...(old.packIds||[]),String(spec.id)])];if(packIds.length!==(old.packIds||[]).length)await put(d,TILES,{...old,packIds});bytes+=old.blob.size}else{const r=await fetcher(offlineTileUrl(t),{cache:'no-store',credentials:'same-origin',signal});if(!r.ok||!r.headers.get('content-type')?.startsWith('image/'))throw Error('No se ha podido descargar una parte del mapa.');const blob=await r.blob();await valid(blob);await put(d,TILES,{...t,blob,bytes:blob.size,packIds:[String(spec.id)],savedAt:base.savedAt});bytes+=blob.size}done++;onProgress?.({completed:done,total:tiles.length,percentage:Math.round(done/tiles.length*100),bytes});if(done%25===0)await put(d,PACKS,{...base,completedTiles:done,totalBytes:bytes})}catch(e){failed=e instanceof Error?e:Error('Descarga incompleta.')}}};try{await Promise.all(Array.from({length:Math.min(WORKERS,tiles.length)},worker));if(failed)throw failed;const finished={...base,completedTiles:done,totalBytes:bytes,status:'ready',savedAt:new Date().toISOString()};await put(d,PACKS,finished);window.dispatchEvent(new CustomEvent('encumbrate:offline-mosaic',{detail:finished}));return finished}catch(e){await put(d,PACKS,{...base,completedTiles:done,totalBytes:bytes,status:'partial'}).catch(()=>{});throw e}finally{d.close()}}
export async function removeOfflinePack(id){const d=await open();try{const p=await get(d,PACKS,String(id));if(!p)return;for(const key of p.tileKeys||[]){const t=await get(d,TILES,key);if(!t)continue;const packIds=(t.packIds||[]).filter(v=>v!==String(id));if(packIds.length)await put(d,TILES,{...t,packIds});else await del(d,TILES,key)}await del(d,PACKS,String(id));window.dispatchEvent(new CustomEvent('encumbrate:offline-mosaic',{detail:{removed:String(id)}}))}finally{d.close()}}
export async function readBestOfflineTile(z,x,y){const d=await open();try{for(let sourceZoom=z;sourceZoom>=5;sourceZoom--){const factor=2**(z-sourceZoom),sx=Math.floor(x/factor),sy=Math.floor(y/factor),record=await get(d,TILES,offlineTileKey(sourceZoom,sx,sy));if(record?.blob?.size)return{record,sourceZoom,factor,subX:x-sx*factor,subY:y-sy*factor}}return null}finally{d.close()}}
export async function hasOfflineMosaicPoint(point,z=15,maxOverzoom=4){if(!point||!finite(point.lat)||!finite(point.lon))return false;const zoom=Math.max(5,Math.min(16,Math.floor(z))),hit=await readBestOfflineTile(zoom,xTile(point.lon,zoom),yTile(point.lat,zoom));return Boolean(hit&&zoom-hit.sourceZoom<=maxOverzoom)}
export function routeOfflineBounds(track,paddingKm=2){const pts=(track?.points||[]).filter(p=>finite(p?.lat)&&finite(p?.lon));if(pts.length<2)throw Error('El trazado no contiene coordenadas suficientes.');let w=Infinity,e=-Infinity,s=Infinity,n=-Infinity;for(const p of pts){w=Math.min(w,+p.lon);e=Math.max(e,+p.lon);s=Math.min(s,+p.lat);n=Math.max(n,+p.lat)}const mid=(s+n)/2,py=Math.max(.01,paddingKm/111),px=Math.max(.01,paddingKm/(111*Math.max(.25,Math.cos(mid*Math.PI/180))));return normalizeOfflineBounds([w-px,s-py,e+px,n+py])}
export async function downloadRouteOfflinePack(track,options={}){if(!track?.id)throw Error('La ruta no tiene identificador.');return downloadOfflinePack({id:`route:${track.id}`,name:track.name||'Ruta',kind:'route',bounds:routeOfflineBounds(track),...OFFLINE_MAP_PROFILES.route},options)}
export const countryOfflinePackSpec=()=>({id:offlineRegionId('country','España'),name:'España completa',kind:'country',bounds:SPAIN_OFFLINE_BOUNDS,...OFFLINE_MAP_PROFILES.country});
