create table if not exists public.social_achievement_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_key text not null,
  title text not null check (char_length(title) between 3 and 80),
  description text not null check (char_length(description) between 10 and 240),
  badge_icon text not null default '🏅' check (char_length(badge_icon) between 1 and 16),
  metadata jsonb not null default '{}'::jsonb,
  achieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(user_id,achievement_key)
);
create index if not exists social_achievement_posts_created_idx on public.social_achievement_posts(created_at desc);
create index if not exists social_achievement_posts_user_idx on public.social_achievement_posts(user_id,created_at desc);
alter table public.social_achievement_posts enable row level security;
revoke all on public.social_achievement_posts from anon,authenticated;
grant select on public.social_achievement_posts to authenticated;
drop policy if exists "authenticated users view official achievements" on public.social_achievement_posts;
create policy "authenticated users view official achievements" on public.social_achievement_posts for select to authenticated using (true);

create or replace function public.publish_route_milestone_achievements() returns trigger
language plpgsql security definer set search_path='' as $$
declare v_routes integer;
begin
  if new.status='completed' and new.trophy_earned=true and (old.status is distinct from 'completed' or old.trophy_earned is distinct from true) then
    select count(*)::integer into v_routes from public.route_activities where user_id=new.user_id and status='completed' and trophy_earned=true;
    if v_routes>=1 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'routes:1','Primer sendero completado','Ha completado y registrado su primera ruta con Encúmbrate.','🥾',jsonb_build_object('routes',1),coalesce(new.ended_at,now())) on conflict(user_id,achievement_key) do nothing; end if;
    if v_routes>=5 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'routes:5','Caminante constante','Ha alcanzado 5 rutas completadas y verificadas por GPS.','🏅',jsonb_build_object('routes',5),coalesce(new.ended_at,now())) on conflict(user_id,achievement_key) do nothing; end if;
    if v_routes>=10 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'routes:10','Explorador Encúmbrate','Ha alcanzado 10 rutas completadas y verificadas por GPS.','🧭',jsonb_build_object('routes',10),coalesce(new.ended_at,now())) on conflict(user_id,achievement_key) do nothing; end if;
    if v_routes>=25 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'routes:25','Aventurero de montaña','Ha alcanzado 25 rutas completadas y verificadas por GPS.','⛰️',jsonb_build_object('routes',25),coalesce(new.ended_at,now())) on conflict(user_id,achievement_key) do nothing; end if;
    if v_routes>=50 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'routes:50','Leyenda del sendero','Ha alcanzado 50 rutas completadas y verificadas por GPS.','🏆',jsonb_build_object('routes',50),coalesce(new.ended_at,now())) on conflict(user_id,achievement_key) do nothing; end if;
  end if;
  return new;
end $$;
revoke all on function public.publish_route_milestone_achievements() from public,anon,authenticated;
drop trigger if exists publish_route_milestone_achievements on public.route_activities;
create trigger publish_route_milestone_achievements after update of status,trophy_earned on public.route_activities for each row execute function public.publish_route_milestone_achievements();

create or replace function public.publish_contribution_achievements() returns trigger
language plpgsql security definer set search_path='' as $$
declare v_contributions integer;
begin
  select count(*)::integer into v_contributions from public.route_contribution_rewards where user_id=new.user_id;
  if v_contributions>=1 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'contributions:1','Creador de caminos','Encúmbrate ha revisado y aprobado su primera ruta aportada.','🗺️',jsonb_build_object('contributions',1),new.awarded_at) on conflict(user_id,achievement_key) do nothing; end if;
  if v_contributions>=5 then insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at) values(new.user_id,'contributions:5','Maestro Encúmbrate','Encúmbrate ha revisado y aprobado 5 rutas aportadas a la comunidad.','👑',jsonb_build_object('contributions',5),new.awarded_at) on conflict(user_id,achievement_key) do nothing; end if;
  return new;
end $$;
revoke all on function public.publish_contribution_achievements() from public,anon,authenticated;
drop trigger if exists publish_contribution_achievements on public.route_contribution_rewards;
create trigger publish_contribution_achievements after insert on public.route_contribution_rewards for each row execute function public.publish_contribution_achievements();

with totals as (select user_id,count(*)::integer routes,max(ended_at) achieved_at from public.route_activities where status='completed' and trophy_earned=true group by user_id), milestones(routes,title,description,badge_icon) as (values (1,'Primer sendero completado','Ha completado y registrado su primera ruta con Encúmbrate.','🥾'),(5,'Caminante constante','Ha alcanzado 5 rutas completadas y verificadas por GPS.','🏅'),(10,'Explorador Encúmbrate','Ha alcanzado 10 rutas completadas y verificadas por GPS.','🧭'),(25,'Aventurero de montaña','Ha alcanzado 25 rutas completadas y verificadas por GPS.','⛰️'),(50,'Leyenda del sendero','Ha alcanzado 50 rutas completadas y verificadas por GPS.','🏆'))
insert into public.social_achievement_posts(user_id,achievement_key,title,description,badge_icon,metadata,achieved_at)
select t.user_id,'routes:'||m.routes,m.title,m.description,m.badge_icon,jsonb_build_object('routes',m.routes),coalesce(t.achieved_at,now()) from totals t join milestones m on t.routes>=m.routes on conflict(user_id,achievement_key) do nothing;

do $$ begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') and not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='social_achievement_posts') then
    alter publication supabase_realtime add table public.social_achievement_posts;
  end if;
end $$;
